/*
 * Java domain class for entity "DocumentUploadDetails" 
 * Created on 2021-09-01 ( Date ISO 2021-09-01 - Time 12:12:04 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.upload.request;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "DocumentUploadDetails"
 *
 * @author Telosys Tools Generator
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class DocumentUploadDetailsDto implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY
	// ----------------------------------------------------------------------
	@JsonProperty("QuoteNo")
	private String claimNo;
	@JsonProperty("Documentref")
	private BigDecimal documentRef;
	@JsonProperty("Doctypeid")
	private String docTypeId;
	@JsonProperty("Productid")
	private BigDecimal productId;
	@JsonProperty("Param")
	private String param;
	@JsonProperty("Insid")
	private BigDecimal insId;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@JsonProperty("Filepathname")
	private String filePathName;
	@JsonProperty("Uploadedtime")
	private Date uploadedTime;
	@JsonProperty("Description")
	private String description;
	@JsonProperty("Status")
	private String status;
	@JsonProperty("Filename")
	private String fileName;
	@JsonProperty("Vtypeid")
	private String vtypeId;
	@JsonProperty("Opstatus")
	private String opStatus;
	@JsonProperty("Opremarks")
	private String opRemarks;
	@JsonProperty("Docid")
	private String docId;
	@JsonProperty("Param2")
	private String param2;
	@JsonProperty("Param3")
	private String param3;
	@JsonProperty("Detect")
	private String detect;
	@JsonProperty("Commonfilepath")
	private String commonFilePath;
	@JsonProperty("Errorres")
	private String errorRes;
	@JsonProperty("Detectperc")
	private BigDecimal detectPerc;
	@JsonProperty("Amendid")
	private BigDecimal amendId;
	@JsonProperty("Createdby")
	private String createdby;

	@JsonProperty("PartyNo")
	private String partyNo;
	@JsonProperty("LossId")
	private String lossId;
	@JsonProperty("Waiveoffyn")
	private String Waiveoffyn;
	@JsonProperty("Remarks")
	private String remarks;
	@JsonProperty("Waiveoffdate")
	private Date waiveoffdate;
	@JsonProperty("Waiveoffby")
	private String waiveoffby;
	@JsonProperty("Waiveoffclaimremarks")
	private String waiveoffclaimremarks;
	
	//UserType
	@JsonProperty("UserType")
	private String usertype;

	
}
