/*
*  Copyright (c) 2019. All right reserved
* Created on 2021-08-20 ( Date ISO 2021-08-20 - Time 12:06:33 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.common.upload.service;
import java.util.List;

import com.maan.common.bean.ClaimDocumentMaster;
import com.maan.common.upload.request.ClaimDocumentMasterReq;
import com.maan.common.upload.response.ClaimDocumentMasterRes;
/**
* <h2>ClaimDocumentMasterServiceimpl</h2>
*/
public interface ClaimDocumentMasterService  {

ClaimDocumentMaster create(ClaimDocumentMaster d);
ClaimDocumentMaster update(ClaimDocumentMaster d);
//ClaimDocumentMaster getOne(long id) ;
 List<ClaimDocumentMaster> getAll();
long getTotal();
//boolean delete(long id);
List<ClaimDocumentMasterRes> getClaimDocumentMaster(ClaimDocumentMasterReq req);

}
