/*
*  Copyright (c) 2019. All right reserved
* Created on 2021-07-31 ( Date ISO 2021-07-31 - Time 18:13:33 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.common.master.service;
import java.util.List;
import com.maan.common.error.Error;

import com.maan.common.bean.MailMaster;
import com.maan.common.master.request.MailMasterReq;
import com.maan.common.master.response.MailMasterRes;
import com.maan.common.master.response.sucessRes;
/**
* <h2>MailMasterServiceimpl</h2>
*/
public interface MailMasterService  {

MailMaster create(MailMaster d);
MailMaster update(MailMaster d);
//MailMaster getOne(long id) ;
 List<MailMaster> getAll();
long getTotal();
//boolean delete(long id);
List<MailMasterRes> getmailmaster(MailMasterReq req);
MailMasterRes getmailmasterid(MailMasterReq req);
sucessRes insertmailmaster(MailMasterReq req);
List<Error> validation(MailMasterReq req);

}
