/*
*  Copyright (c) 2019. All right reserved
* Created on 2021-11-19 ( Date ISO 2021-11-19 - Time 13:16:54 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.common.master.service;
import java.util.List;
import com.maan.common.error.Error;

import com.maan.common.bean.SmsConfigMaster;
import com.maan.common.master.request.SmsConfigMasterReq;
import com.maan.common.master.response.SmsConfigMasterRes;
import com.maan.common.master.response.sucessRes;
/**
* <h2>SmsConfigMasterServiceimpl</h2>
*/
public interface SmsConfigMasterService  {

SmsConfigMaster create(SmsConfigMaster d);
SmsConfigMaster update(SmsConfigMaster d);
//SmsConfigMaster getOne(long id) ;
 List<SmsConfigMaster> getAll();
long getTotal();
//boolean delete(long id);
List<SmsConfigMasterRes> getsmsconfigmaster(SmsConfigMasterReq req);
SmsConfigMasterRes getsmsconfigmasterid(SmsConfigMasterReq req);
sucessRes insertsmsconfigmaster(SmsConfigMasterReq req);
List<Error> validation(SmsConfigMasterReq req);

}
