/*
 * Java domain class for entity "BranchMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:47 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;

import lombok.*;
import java.math.BigDecimal;
import java.util.Date;


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * Domain class for entity "BranchMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class BranchMasterDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Branchcode")
    private String     branchCode   ;
	@JsonProperty("Regioncode")
    private String     regionCode   ;
	@JsonProperty("Inscompanyid")
    private BigDecimal insCompanyId ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Branchname")
    private String     branchName   ;
	@JsonProperty("Address1")
    private String     address1     ;
	@JsonProperty("Address2")
    private String     address2     ;
	@JsonProperty("Address3")
    private String     address3     ;
	@JsonProperty("City")
    private String     city         ;
	@JsonProperty("Country")
    private String     country      ;
	@JsonProperty("Phone")
    private String     phone        ;
	@JsonProperty("Email")
    private String     email        ;
	@JsonProperty("Belongingtype")
    private String     belongingType ;
	@JsonProperty("Belongingbranch")
    private String     belongingBranch ;
	@JsonProperty("Coreappcode")
    private String     coreAppCode  ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Effectivedate")
    private Date       effectiveDate ;
	@JsonProperty("Remarks")
    private String     remarks      ;
	@JsonProperty("Amendid")
    private BigDecimal amendId      ;
	@JsonProperty("Fax")
    private BigDecimal fax          ;
	@JsonProperty("Headerimg")
    private String     headerImg    ;
	@JsonProperty("Footerimg")
    private String     footerImg    ;
	@JsonProperty("Signimg")
    private String     signImg      ;
	@JsonProperty("Stamp")
    private String     stamp        ;
	@JsonProperty("Currencyname")
    private String     currencyName ;
	@JsonProperty("Currencyabbreviation")
    private String     currencyAbbreviation ;
	@JsonProperty("Currencyacronym")
    private String     currencyAcronym ;
	@JsonProperty("Originationcountryid")
    private BigDecimal originationCountryId ;
	@JsonProperty("Destinationcountryid")
    private BigDecimal destinationCountryId ;
	@JsonProperty("Currencydecimalname")
    private String     currencyDecimalName ;
	@JsonProperty("Currencydecimaldigit")
    private BigDecimal currencyDecimalDigit ;
	@JsonProperty("Decimalplaces")
    private BigDecimal decimalPlaces ;
	@JsonProperty("Tax")
    private BigDecimal tax          ;
	@JsonProperty("Branchprefix")
    private String     branchPrefix ;
	@JsonProperty("Pckeyclosetrn")
    private String     pckeyCloseTrn ;
	@JsonProperty("Longitudeyn")
    private String     longitudeYn  ;
	@JsonProperty("Deptcode")
    private String     deptCode     ;
	@JsonProperty("Exchangeid")
    private BigDecimal exchangeId   ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
