/*
 * Java domain class for entity "BrokerCompanyMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:47 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.maan.common.bean.BrokerMaster;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "BrokerCompanyMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class BrokerCompanyMasterDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Agencycode")
    private String     agencyCode   ;
	@JsonProperty("Inscompanyid")
    private BigDecimal insCompanyId ;
	@JsonProperty("Brokercode")
    private String     brokerCode   ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Companyname")
    private String     companyName  ;
	@JsonProperty("Contactperson")
    private String     contactPerson ;
	@JsonProperty("Address1")
    private String     address1     ;
	@JsonProperty("Address2")
    private String     address2     ;
	@JsonProperty("Address3")
    private String     address3     ;
	@JsonProperty("City")
    private String     city         ;
	@JsonProperty("Country")
    private String     country      ;
	@JsonProperty("Phone")
    private String     phone        ;
	@JsonProperty("Pobox")
    private BigDecimal pobox        ;
	@JsonProperty("Fax")
    private String     fax          ;
	@JsonProperty("Customerid")
    private BigDecimal customerId   ;
	@JsonProperty("Branchcode")
    private String     branchCode   ;
	@JsonProperty("Acexecutiveid")
    private BigDecimal acExecutiveId ;
	@JsonProperty("Brokertype")
    private String     brokerType   ;
	@JsonProperty("Sourcecode")
    private String     sourceCode   ;
	@JsonProperty("Sourcetype")
    private String     sourceType   ;
	@JsonProperty("Modeofpay")
    private String     modeofpay    ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Remarks")
    private String     remarks      ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@JsonProperty("Brokermaster")
    private BrokerMaster brokerMaster ;

      
	  
	  
}
