/*
 * Java domain class for entity "BrokerCommissionMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:47 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.maan.common.bean.BrokerMaster;
import com.maan.common.bean.PolicytypeMaster;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "BrokerCommissionMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class BrokerCommissionMasterDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Agencycode")
    private String     agencyCode   ;
	@JsonProperty("Inscompanyid")
    private BigDecimal insCompanyId ;
	@JsonProperty("Productid")
    private BigDecimal productId    ;
	@JsonProperty("Policytypeid")
    private BigDecimal policytypeId ;
	@JsonProperty("Amendid")
    private BigDecimal amendId      ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Suminsuredstart")
    private BigDecimal suminsuredStart ;
	@JsonProperty("Suminsuredend")
    private BigDecimal suminsuredEnd ;
	@JsonProperty("Commissionpercentage")
    private BigDecimal commissionPercentage ;
	@JsonProperty("Checkeryn")
    private String     checkerYn    ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Effectivedate")
    private Date       effectiveDate ;
	@JsonProperty("Enddate")
    private Date       endDate      ;
	@JsonProperty("Otherfee1")
    private BigDecimal otherFee1    ;
	@JsonProperty("Otherfee2")
    private BigDecimal otherFee2    ;
	@JsonProperty("Otherfee3")
    private BigDecimal otherFee3    ;
	@JsonProperty("Vatpercent")
    private BigDecimal vatpercent   ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@JsonProperty("Policytypemaster")
    private PolicytypeMaster policytypeMaster ;
	@JsonProperty("Brokermaster")
    private BrokerMaster brokerMaster ;

      
	  
	  
}
