/*
 * Java domain class for entity "BrokerMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:47 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.maan.common.bean.BrokerCommissionMaster;
import com.maan.common.bean.BrokerCompanyMaster;
import com.maan.common.bean.LoginMaster;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "BrokerMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class BrokerMasterDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Agencycode")
    private String     agencyCode   ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Branchcode")
    private String     branchCode   ;
	@JsonProperty("Policyfeestatus")
    private String     policyFeeStatus ;
	@JsonProperty("Taxstatus")
    private String     taxStatus    ;
	@JsonProperty("Vatstatus")
    private String     vatStatus    ;
	@JsonProperty("Policyfee")
    private BigDecimal policyFee    ;
	@JsonProperty("Tax")
    private BigDecimal tax          ;
	@JsonProperty("Vat")
    private BigDecimal vat          ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Expirydate")
    private Date       expiryDate   ;
	@JsonProperty("Remarks")
    private String     remarks      ;
	@JsonProperty("Inscompanyid")
    private BigDecimal insCompanyId ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@JsonProperty("Listofloginmaster")
    private List<LoginMaster> listOfLoginMaster ;
	@JsonProperty("Listofbrokercommissionmaster")
    private List<BrokerCommissionMaster> listOfBrokerCommissionMaster ;
	@JsonProperty("Listofbrokercompanymaster")
    private List<BrokerCompanyMaster> listOfBrokerCompanyMaster ;

      
	  
	  
}
