/*
 * Java domain class for entity "CoverageMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "CoverageMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class CoverageMasterDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Mccoverid")
    private BigDecimal mcCoverid    ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Mcfieldname")
    private String     mcFieldname  ;
	@JsonProperty("Mcfieldlabelname")
    private String     mcFieldlabelname ;
	@JsonProperty("Mcinputfield")
    private String     mcInputfield ;
	@JsonProperty("Mcoptions")
    private String     mcOptions    ;
	@JsonProperty("Mcdatatype")
    private String     mcDatatype   ;
	@JsonProperty("Mclength")
    private BigDecimal mcLength     ;
	@JsonProperty("Mcmandatory")
    private String     mcMandatory  ;
	@JsonProperty("Mcdatetypeformat")
    private String     mcDatetypeformat ;
	@JsonProperty("Mcvalidationmessage")
    private String     mcValidationmessage ;
	@JsonProperty("Mcparentid")
    private BigDecimal mcParentid   ;
	@JsonProperty("Mcapiurl")
    private String     mcApiurl     ;
	@JsonProperty("Mcvalue")
    private String     mcValue      ;
	@JsonProperty("Mcparentname")
    private String     mcParentname ;
	@JsonProperty("Mcchildname")
    private String     mcChildname  ;
	@JsonProperty("Mccascadingoptions")
    private String     mcCascadingoptions ;
	@JsonProperty("Mcstatus")
    private String     mcStatus     ;
	@JsonProperty("Mcentrydate")
    private Date       mcEntrydate  ;
	@JsonProperty("Mcsequenceyn")
    private String     mcSequenceyn ;
	@JsonProperty("Mcdisplayorder")
    private String     mcDisplayOrder ;
	@JsonProperty("Mcrequesttype")
    private String     mcRequesttype ;
	@JsonProperty("Mcrequestkeys")
    private String     mcRequestkeys ;
	@JsonProperty("Mcrequestvalues")
    private String     mcRequestvalues ;
	@JsonProperty("Tooltipmes")
    private String     tooltipMes   ;
	@JsonProperty("Coveragetype")
    private String     coveragetype ;
	@JsonProperty("Uploadoption")
    private String     uploadoption ;
	@JsonProperty("Maxsuminsured")
    private BigDecimal maxsuminsured ;
	@JsonProperty("Coveragelimit")
    private BigDecimal coveragelimit ;
	@JsonProperty("Calctype")
    private String     calctype     ;
	@JsonProperty("Calcstatus")
    private String     calcstatus   ;
	@JsonProperty("Effectivedate")
    private Date       effectivedate ;
	@JsonProperty("Corecode")
    private String     corecode     ;
	@JsonProperty("Mcoptionkeys")
    private String     mcOptionkeys ;
	@JsonProperty("Mcoptionvalues")
    private String     mcOptionvalues ;
	@JsonProperty("Baserate")
    private String     baseRate     ;
	@JsonProperty("Calcyn")
    private String     calcYn       ;
	@JsonProperty("Excess")
    private String     excess       ;
	@JsonProperty("Minpremium")
    private String     minPremium   ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
