/*
 * Java domain class for entity "EserviceRequestDetail" 
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:39 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.maan.common.bean.EserviceVehicleDetail;
import com.maan.common.bean.MsCustomerDetail;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "EserviceRequestDetail"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class EserviceRequestDetailDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Requestreferenceno")
    private String     requestreferenceno ;
	@JsonProperty("Customerid")
    private BigDecimal customerId   ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Insurancecompanycode")
    private String     insurancecompanycode ;
	@JsonProperty("Loginid")
    private String     loginId      ;
	@JsonProperty("Applicationid")
    private String     applicationId ;
	@JsonProperty("Agencycode")
    private String     agencyCode   ;
	@JsonProperty("Brokercode")
    private String     brokerCode   ;
	@JsonProperty("Executiveid")
    private String     executiveId  ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Quoteno")
    private BigDecimal quoteNo      ;
	@JsonProperty("Applicationno")
    private BigDecimal applicationNo ;
	@JsonProperty("Quotecreateddate")
    private Date       quoteCreatedDate ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Policystartdate")
    private Date       policystartdate ;
	@JsonProperty("Policyno")
    private String     policyNo     ;
	@JsonProperty("Vehicleid")
    private BigDecimal vehicleId    ;
	@JsonProperty("Policytype")
    private String     policytype   ;
	@JsonProperty("Productid")
    private BigDecimal productId    ;
	@JsonProperty("Opcoverselected")
    private String     opcoverSelected ;
	@JsonProperty("Ebrokerid")
    private BigDecimal ebrokerId    ;
	@JsonProperty("Insuredname")
    private String     insuredName  ;
	@JsonProperty("Dateofbirthg")
    private String     dateofbirthg ;
	@JsonProperty("Dateofbirthh")
    private String     dateofbirthh ;
	@JsonProperty("Mobile")
    private String     mobile       ;
	@JsonProperty("Email")
    private String     email        ;
	@JsonProperty("Gender")
    private String     gender       ;
	@JsonProperty("Premium")
    private BigDecimal premium      ;
	@JsonProperty("Validationremarks")
    private String     validationRemarks ;
	@JsonProperty("Policyholderid")
    private String     policyholderid ;
	@JsonProperty("Previousowneriqamaid")
    private String     previousowneriqamaid ;
	@JsonProperty("Sequenceno")
    private String     sequenceno   ;
	@JsonProperty("Customsid")
    private String     customsid    ;
	@JsonProperty("Ownerdriveryn")
    private String     ownerdriveryn ;
	@JsonProperty("Transferowner")
    private String     transferowner ;
	@JsonProperty("Previousownertitle")
    private String     previousownertitle ;
	@JsonProperty("Previousownername")
    private String     previousownername ;
	@JsonProperty("Vehicleplatetype")
    private String     vehicleplatetype ;
	@JsonProperty("Vehtypeid")
    private BigDecimal vehTypeId    ;
	@JsonProperty("Vehmakeid")
    private BigDecimal vehMakeId    ;
	@JsonProperty("Vehmodelid")
    private BigDecimal vehModelId   ;
	@JsonProperty("Vehbodyid")
    private BigDecimal vehBodyId    ;
	@JsonProperty("Vehmanfcountry")
    private BigDecimal vehManfCountry ;
	@JsonProperty("Vehweight")
    private BigDecimal vehWeight    ;
	@JsonProperty("Vehcc")
    private BigDecimal vehCc        ;
	@JsonProperty("Vehengineno")
    private String     vehEngineNo  ;
	@JsonProperty("Vehchassisno")
    private String     vehChassisNo ;
	@JsonProperty("Vehplatechar")
    private BigDecimal vehPlateChar ;
	@JsonProperty("Vehplatenumber")
    private BigDecimal vehPlateNumber ;
	@JsonProperty("Vehseating")
    private BigDecimal vehSeating   ;
	@JsonProperty("Noofclaims")
    private BigDecimal noOfClaims   ;
	@JsonProperty("Noclaimbonus")
    private BigDecimal noClaimBonus ;
	@JsonProperty("Claimedamount")
    private BigDecimal claimedAmount ;
	@JsonProperty("Manfactureyear")
    private BigDecimal manfactureyear ;
	@JsonProperty("Vehregndate")
    private String     vehRegnDate  ;
	@JsonProperty("Suminsured")
    private String     suminsured   ;
	@JsonProperty("Excess")
    private String     excess       ;
	@JsonProperty("Deductible")
    private BigDecimal deductible   ;
	@JsonProperty("Havepromocode")
    private String     havepromocode ;
	@JsonProperty("Promocode")
    private String     promocode    ;
	@JsonProperty("Importyn")
    private String     importYn     ;
	@JsonProperty("Importcode")
    private BigDecimal importCode   ;
	@JsonProperty("Gcctype")
    private BigDecimal gccType      ;
	@JsonProperty("Occupation")
    private BigDecimal occupation   ;
	@JsonProperty("Vehparkingtype")
    private String     vehParkingType ;
	@JsonProperty("Referralremarks")
    private String     referralRemarks ;
	@JsonProperty("Phncb")
    private BigDecimal phNcb        ;
	@JsonProperty("Phlicage")
    private BigDecimal phLicAge     ;
	@JsonProperty("Loyalflag")
    private String     loyalFlag    ;
	@JsonProperty("Loyaltypercent")
    private BigDecimal loyaltyPercent ;
	@JsonProperty("Claimyn")
    private String     claimYn      ;
	@JsonProperty("Claimratio")
    private BigDecimal claimRatio   ;
	@JsonProperty("Renewaloldexpdate")
    private Date       renewalOldExpDate ;
	@JsonProperty("Renewaloldpolicy")
    private String     renewalOldPolicy ;
	@JsonProperty("Promotype")
    private String     promotype    ;
	@JsonProperty("Schemeempcode")
    private String     schemeEmpCode ;
	@JsonProperty("Vehcylinders")
    private BigDecimal vehCylinders ;
	@JsonProperty("Priceid")
    private String     priceId      ;
	@JsonProperty("Quotetype")
    private String     quoteType    ;
	@JsonProperty("Policyenddate")
    private Date       policyenddate ;
	@JsonProperty("Integrationstatus")
    private String     integrationStatus ;
	@JsonProperty("Otheroccupation")
    private String     otheroccupation ;
	@JsonProperty("Lapsedremarks")
    private String     lapsedRemarks ;
	@JsonProperty("Lapseddate")
    private Date       lapsedDate   ;
	@JsonProperty("Branchcode")
    private String     branchCode   ;
	@JsonProperty("Vehiclecondition")
    private String     vehicleCondition ;
	@JsonProperty("Vehiclemileage")
    private String     vehicleMileage ;
	@JsonProperty("Channellist")
    private String     channelList  ;
	@JsonProperty("Schemeyn")
    private String     schemeyn     ;
	@JsonProperty("Agencytype")
    private String     agencytype   ;
	@JsonProperty("Chassisno")
    private String     chassisno    ;
	@JsonProperty("Severitylevel")
    private BigDecimal severitylevel ;
	@JsonProperty("Claimflag")
    private String     claimflag    ;
	@JsonProperty("Comuserdisc1")
    private BigDecimal comUserDisc1 ;
	@JsonProperty("Comuserdisc2")
    private BigDecimal comUserDisc2 ;
	@JsonProperty("Comuserdisc3")
    private BigDecimal comUserDisc3 ;
	@JsonProperty("Claimsloading")
    private BigDecimal claimsLoading ;
	@JsonProperty("Jointname")
    private String     jointName    ;
	@JsonProperty("Sourcetype")
    private String     sourceType   ;
	@JsonProperty("Customercode")
    private String     customerCode ;
	@JsonProperty("Customercodename")
    private String     customerCodename ;
	@JsonProperty("Vehicleusageid")
    private BigDecimal vehicleUsageId ;
	@JsonProperty("Modelname")
    private String     modelName    ;
	@JsonProperty("Iscommercialyn")
    private String     iscommercialYn ;
	@JsonProperty("Custapprovestatus")
    private String     custApproveStatus ;
	@JsonProperty("Custrejectremarks")
    private String     custRejectRemarks ;
	@JsonProperty("Custapprovedate")
    private Date       custApproveDate ;
	@JsonProperty("Curryearmileage")
    private String     currYearMileage ;
	@JsonProperty("Noofdriver")
    private String     noOfDriver   ;
	@JsonProperty("Greyimportyn")
    private String     greyImportYn ;
	@JsonProperty("Volumediscount")
    private String     volumeDiscount ;
	@JsonProperty("Bdmcode")
    private String     bdmCode      ;
	@JsonProperty("Whatsappcode")
    private String     whatsappCode ;
	@JsonProperty("Whatsappno")
    private BigDecimal whatsappNo   ;
	@JsonProperty("Renewalyn")
    private String     renewalYn    ;
	@JsonProperty("Renewalpolicyno")
    private String     renewalPolicyno ;
	@JsonProperty("Renewalclaimamt")
    private BigDecimal renewalClaimamt ;
	@JsonProperty("Platenationalty")
    private BigDecimal plateNationalty ;
	@JsonProperty("Noofdays")
    private BigDecimal noofdays     ;
	@JsonProperty("Nationality")
    private BigDecimal nationality  ;
	@JsonProperty("Mobilecode")
    private String     mobileCode   ;
	@JsonProperty("Finalizeyn")
    private String     finalizeYn   ;
	@JsonProperty("Visa")
    private BigDecimal visa         ;
	@JsonProperty("Wilayat")
    private BigDecimal wilayat      ;
	@JsonProperty("Issalvageyn")
    private String     isSalvageyn  ;
	@JsonProperty("Targetprice")
    private BigDecimal targetPrice  ;
	@JsonProperty("Premiumloading")
    private BigDecimal premiumLoading ;
	@JsonProperty("Premiumdiscount")
    private BigDecimal premiumDiscount ;
	@JsonProperty("Oldapplicationid")
    private String     oldApplicationId ;
	@JsonProperty("Extraopcoverselected")
    private String     extraOpcoverSelected ;
	@JsonProperty("Imgrefno")
    private String     imgrefNo     ;
	@JsonProperty("Interestedincompyn")
    private String     interestedinCompyn ;
	@JsonProperty("Stillwantcompyn")
    private String     stillwantCompyn ;
	@JsonProperty("Extraaddonpremium")
    private BigDecimal extraAddonPremium ;
	@JsonProperty("Prevpolicytype")
    private String     prevPolicytype ;
	@JsonProperty("Overallpremium")
    private BigDecimal overallPremium ;
	@JsonProperty("Userloginid")
    private String     userLoginid  ;
	@JsonProperty("Logouttime")
    private Date       logoutTime   ;
	@JsonProperty("Drivingtype")
    private BigDecimal drivingType  ;
	@JsonProperty("Aggrreferenceid")
    private String     aggrReferenceid ;
	@JsonProperty("Electricalsi")
    private BigDecimal electricalSi ;
	@JsonProperty("Nonelectricalsi")
    private BigDecimal nonelectricalSi ;
	@JsonProperty("Currencyid")
    private BigDecimal currencyId   ;
	@JsonProperty("Currencytype")
    private String     currencyType ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@JsonProperty("Listofeservicevehicledetail")
    private List<EserviceVehicleDetail> listOfEserviceVehicleDetail ;
	@JsonProperty("Mscustomerdetail")
    private MsCustomerDetail msCustomerDetail ;

      
	  
	  
}
