/*
 * Java domain class for entity "InsuranceCompanyMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.maan.common.bean.LoginMaster;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "InsuranceCompanyMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class InsuranceCompanyMasterDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Insid")
    private BigDecimal insId        ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Insname")
    private String     insName      ;
	@JsonProperty("Insaddress")
    private String     insAddress   ;
	@JsonProperty("Inscountry")
    private BigDecimal insCountry   ;
	@JsonProperty("Inscity")
    private BigDecimal insCity      ;
	@JsonProperty("Inszipcode")
    private String     insZipcode   ;
	@JsonProperty("Insphone")
    private String     insPhone     ;
	@JsonProperty("Insemail")
    private String     insEmail     ;
	@JsonProperty("Inswebsite")
    private String     insWebsite   ;
	@JsonProperty("Insimagelogo")
    private String     insImageLogo ;
	@JsonProperty("Inscoreappcode")
    private String     insCoreAppcode ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Expirydate")
    private Date       expiryDate   ;
	@JsonProperty("Remarks")
    private String     remarks      ;
	@JsonProperty("Insregioncode")
    private String     insRegionCode ;
	@JsonProperty("Latitue")
    private String     latitue      ;
	@JsonProperty("Longtitue")
    private String     longtitue    ;
	@JsonProperty("Effectivedate")
    private Date       effectiveDate ;
	@JsonProperty("Amendid")
    private BigDecimal amendid      ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@JsonProperty("Listofloginmaster")
    private List<LoginMaster> listOfLoginMaster ;

      
	  
	  
}
