/*
 * Java domain class for entity "LoginMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.maan.common.bean.BrokerMaster;
import com.maan.common.bean.InsuranceCompanyMaster;
import com.maan.common.bean.LoginUserDetails;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "LoginMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class LoginMasterDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Loginid")
    private String     loginId      ;
	@JsonProperty("Usertype")
    private String     usertype     ;
	@JsonProperty("Agencycode")
    private String     agencyCode   ;
	@JsonProperty("Companyid")
    private BigDecimal companyId    ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Regioncode")
    private String     regionCode   ;
	@JsonProperty("Branchcode")
    private String     branchCode   ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Password")
    private String     password     ;
	@JsonProperty("Username")
    private String     username     ;
	@JsonProperty("Userid")
    private BigDecimal userid       ;
	@JsonProperty("Oacode")
    private String     oaCode       ;
	@JsonProperty("Accesstype")
    private String     accesstype   ;
	@JsonProperty("Rights")
    private String     rights       ;
	@JsonProperty("Lpass1")
    private String     lpass1       ;
	@JsonProperty("Lpass2")
    private String     lpass2       ;
	@JsonProperty("Lpass3")
    private String     lpass3       ;
	@JsonProperty("Passdate")
    private Date       passdate     ;
	@JsonProperty("Createdby")
    private String     createdBy    ;
	@JsonProperty("Useridcreation")
    private String     userIdCreation ;
	@JsonProperty("Acexecutivecreation")
    private String     acExecutiveCreation ;
	@JsonProperty("Remarks")
    private String     remarks      ;
	@JsonProperty("Referal")
    private String     referal      ;
	@JsonProperty("Statecode")
    private String     stateCode    ;
	@JsonProperty("Countryid")
    private BigDecimal countryId    ;
	@JsonProperty("Lpass4")
    private String     lpass4       ;
	@JsonProperty("Lpass5")
    private String     lpass5       ;
	@JsonProperty("Menuid")
    private String     menuId       ;
	@JsonProperty("Productid")
    private String     productId    ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Inceptiondate")
    private Date       inceptionDate ;
	@JsonProperty("Expirydate")
    private Date       expiryDate   ;
	@JsonProperty("Brokercodes")
    private String     brokerCodes  ;
	@JsonProperty("Fdcode")
    private String     fdCode       ;
	@JsonProperty("Coreloginid")
    private String     coreLoginId  ;
	@JsonProperty("Appid")
    private String     appId        ;
	@JsonProperty("Pwdcount")
    private String     pwdCount     ;
	@JsonProperty("Usermail")
    private String     userMail     ;
	@JsonProperty("Attacheduw")
    private String     attachedUw   ;
	@JsonProperty("Attachedbranch")
    private String     attachedBranch ;
	@JsonProperty("Restictipstatus")
    private String     restictIpStatus ;
	@JsonProperty("Allowedipaddr")
    private String     allowedIpAddr ;
	@JsonProperty("Employecode")
    private String     employeCode  ;
	@JsonProperty("Mobilenumber")
    private String     mobileNumber ;
	@JsonProperty("Suminsuredstart")
    private BigDecimal suminsuredStart ;
	@JsonProperty("Suminsuredend")
    private BigDecimal suminsuredEnd ;
	@JsonProperty("Subusertype")
    private String     subUserType  ;
	@JsonProperty("Wajahyn")
    private String     wajahYn      ;
	@JsonProperty("Encryptpassword")
    private String     encryptPassword ;
	@JsonProperty("Tokenpassword")
    private String     tokenPassword ;
	@JsonProperty("Subbranch")
    private String     subBranch    ;
	@JsonProperty("Losstypeidlist")
    private String     losstypeidlist ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@JsonProperty("Insurancecompanymaster")
    private InsuranceCompanyMaster insuranceCompanyMaster ;
	@JsonProperty("Listofloginuserdetails")
    private List<LoginUserDetails> listOfLoginUserDetails ;
	@JsonProperty("Brokermaster")
    private BrokerMaster brokerMaster ;

      
	  
	  
}
