/*
 * Java domain class for entity "LoginUserDetails" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.maan.common.bean.LoginMaster;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "LoginUserDetails"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class LoginUserDetailsDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Loginid")
    private String     loginId      ;
	@JsonProperty("Companyid")
    private BigDecimal companyId    ;
	@JsonProperty("Productid")
    private BigDecimal productId    ;
	@JsonProperty("Agencycode")
    private String     agencyCode   ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Policytypeid")
    private String     policytypeId ;
	@JsonProperty("Oacode")
    private String     oaCode       ;
	@JsonProperty("Menuid")
    private String     menuId       ;
	@JsonProperty("Accesstype")
    private String     accessType   ;
	@JsonProperty("Countryid")
    private BigDecimal countryId    ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Expirydate")
    private Date       expiryDate   ;
	@JsonProperty("Remarks")
    private String     remarks      ;
	/*@JsonProperty("branchcode")
	// Attribute "branchCode" is a link 
	@JsonProperty("status")
	// Attribute "status" is a link 
	@JsonProperty("usertype")
	// Attribute "usertype" is a link 
	@JsonProperty("regioncode")
	// Attribute "regionCode" is a link  */

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@JsonProperty("Loginmaster")
    private LoginMaster loginMaster  ;

      
	  
	  
}
