/*
 * Java domain class for entity "MField" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "MField"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class MFieldDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Mfmoduleid")
    private BigDecimal mfModuleid   ;
	@JsonProperty("Mfscreenid")
    private BigDecimal mfScreenid   ;
	@JsonProperty("Mfsubscreenid")
    private BigDecimal mfSubscreenid ;
	@JsonProperty("Mffieldid")
    private BigDecimal mfFieldid    ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Mffieldname")
    private String     mfFieldname  ;
	@JsonProperty("Mffieldlabelname")
    private String     mfFieldlabelname ;
	@JsonProperty("Mfinputfield")
    private String     mfInputfield ;
	@JsonProperty("Mfoptions")
    private String     mfOptions    ;
	@JsonProperty("Mfdatatype")
    private String     mfDatatype   ;
	@JsonProperty("Mflength")
    private BigDecimal mfLength     ;
	@JsonProperty("Mfmandatory")
    private String     mfMandatory  ;
	@JsonProperty("Mfdatetypeformat")
    private String     mfDatetypeformat ;
	@JsonProperty("Mfvalidationmessage")
    private String     mfValidationmessage ;
	@JsonProperty("Mfparentid")
    private BigDecimal mfParentid   ;
	@JsonProperty("Mfapiurl")
    private String     mfApiurl     ;
	@JsonProperty("Mfvalue")
    private String     mfValue      ;
	@JsonProperty("Mfparentname")
    private String     mfParentname ;
	@JsonProperty("Mfchildname")
    private String     mfChildname  ;
	@JsonProperty("Mfcascadingoptions")
    private String     mfCascadingoptions ;
	@JsonProperty("Mfstatus")
    private String     mfStatus     ;
	@JsonProperty("Mfentrydate")
    private Date       mfEntrydate  ;
	@JsonProperty("Mfsequenceyn")
    private String     mfSequenceyn ;
	@JsonProperty("Mfdisplayorder")
    private String     mfDisplayOrder ;
	@JsonProperty("Mfrequesttype")
    private String     mfRequesttype ;
	@JsonProperty("Mfrequestkeys")
    private String     mfRequestkeys ;
	@JsonProperty("Mfrequestvalues")
    private String     mfRequestvalues ;
	@JsonProperty("Tooltipmes")
    private String     tooltipMes   ;
	@JsonProperty("Coveragetype")
    private String     coveragetype ;
	@JsonProperty("Uploadoption")
    private String     uploadoption ;
	@JsonProperty("Maxsuminsured")
    private BigDecimal maxsuminsured ;
	@JsonProperty("Coveragelimit")
    private BigDecimal coveragelimit ;
	@JsonProperty("Calctype")
    private String     calctype     ;
	@JsonProperty("Calcstatus")
    private String     calcstatus   ;
	@JsonProperty("Effectivedate")
    private Date       effectivedate ;
	@JsonProperty("Corecode")
    private String     corecode     ;
	@JsonProperty("Mfoptionkeys")
    private String     mfOptionkeys ;
	@JsonProperty("Mfoptionvalues")
    private String     mfOptionvalues ;
	@JsonProperty("Baserate")
    private String     baseRate     ;
	@JsonProperty("Calcyn")
    private String     calcYn       ;
	@JsonProperty("Excess")
    private String     excess       ;
	@JsonProperty("Minpremium")
    private String     minPremium   ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
