/*
 * Java domain class for entity "MModule" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "MModule"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class MModuleDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Mmmoduleid")
    private BigDecimal mmModuleid   ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Mmmodulename")
    private String     mmModulename ;
	@JsonProperty("Mccoreappcode")
    private String     mcCoreappcode ;
	@JsonProperty("Mmcompanyid")
    private BigDecimal mmCompanyid  ;
	@JsonProperty("Mmloginurl")
    private String     mmLoginurl   ;
	@JsonProperty("Mmeffectivedate")
    private Date       mmEffectivedate ;
	@JsonProperty("Mmentrydate")
    private Date       mmEntrydate  ;
	@JsonProperty("Mmstatus")
    private String     mmStatus     ;
	@JsonProperty("Mmdisplayorder")
    private BigDecimal mmDisplayorder ;
	@JsonProperty("Mmremarks")
    private String     mmRemarks    ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
