/*
 * Java domain class for entity "MScreen" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "MScreen"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class MScreenDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Msmoduleid")
    private BigDecimal msModuleid   ;
	@JsonProperty("Msscreenid")
    private BigDecimal msScreenid   ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Msscreenname")
    private String     msScreenname ;
	@JsonProperty("Mssaveurl")
    private String     msSaveurl    ;
	@JsonProperty("Msgeturl")
    private String     msGeturl     ;
	@JsonProperty("Mslisturl")
    private String     msListurl    ;
	@JsonProperty("Mseffectivedate")
    private Date       msEffectivedate ;
	@JsonProperty("Msentrydate")
    private Date       msEntrydate  ;
	@JsonProperty("Msstatus")
    private String     msStatus     ;
	@JsonProperty("Msdisplayorder")
    private BigDecimal msDisplayorder ;
	@JsonProperty("Msremarks")
    private String     msRemarks    ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
