/*
 * Java domain class for entity "MSubscreen" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "MSubscreen"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class MSubscreenDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Mssmoduleid")
    private BigDecimal mssModuleid  ;
	@JsonProperty("Mssscreenid")
    private BigDecimal mssScreenid  ;
	@JsonProperty("Msssubscreenid")
    private BigDecimal mssSubscreenid ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Msssubscreenname")
    private String     mssSubscreenname ;
	@JsonProperty("Mssgriddata")
    private String     mssGriddata  ;
	@JsonProperty("Mssgridyn")
    private String     mssGridyn    ;
	@JsonProperty("Mssgridurl")
    private String     mssGridurl   ;
	@JsonProperty("Msseffectivedate")
    private Date       mssEffectivedate ;
	@JsonProperty("Mssentrydate")
    private Date       mssEntrydate ;
	@JsonProperty("Mssstatus")
    private String     mssStatus    ;
	@JsonProperty("Mssdisplayorder")
    private BigDecimal mssDisplayorder ;
	@JsonProperty("Mssremarks")
    private String     mssRemarks   ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
