/*
 * Java domain class for entity "OfsConfigMaster" 
 * Created on 2022-01-22 ( Date ISO 2022-01-22 - Time 18:25:35 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;

import lombok.*;
import java.math.BigDecimal;


import java.math.BigDecimal;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * Domain class for entity "OfsConfigMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class OfsConfigMasterDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Ofsconfigid")
    private BigDecimal ofsConfigId  ;
	@JsonProperty("Productid")
    private BigDecimal productId    ;
	@JsonProperty("Schemeid")
    private BigDecimal schemeId     ;
	@JsonProperty("Coveragesid")
    private BigDecimal coveragesId  ;
	@JsonProperty("Coveragessubid")
    private BigDecimal coveragesSubId ;
	@JsonProperty("Moduleid")
    private BigDecimal moduleId     ;
	@JsonProperty("Screenid")
    private BigDecimal screenId     ;
	@JsonProperty("Subscreenid")
    private BigDecimal subscreenId  ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Contenttypeid")
    private BigDecimal contentTypeId ;
	@JsonProperty("Displayname")
    private String     displayName  ;
	@JsonProperty("Displaytype")
    private String     displayType  ;
	@JsonProperty("Displayorder")
    private BigDecimal displayOrder ;
	@JsonProperty("Dropdownkey")
    private String     dropdownKey  ;
	@JsonProperty("Dropdownvalue")
    private String     dropdownValue ;
	@JsonProperty("Dropdowntable")
    private String     dropdownTable ;
	@JsonProperty("Validationtype")
    private String     validationType ;
	@JsonProperty("Desttable")
    private String     destTable    ;
	@JsonProperty("Destcolumn")
    private String     destColumn   ;
	@JsonProperty("Amendid")
    private BigDecimal amendId      ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Mandatory")
    private String     mandatory    ;
	@JsonProperty("Totalsuminsuredyn")
    private String     totalSuminsuredYn ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
