/*
 * Java domain class for entity "OfsData" 
 * Created on 2022-01-19 ( Date ISO 2022-01-19 - Time 12:54:42 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;

import lombok.*;
import java.math.BigDecimal;
import java.util.Date;


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * Domain class for entity "OfsData"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class OfsDataDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Quoteno")
    private BigDecimal quoteNo      ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Amendid")
    private BigDecimal amendId      ;
	@JsonProperty("Customerid")
    private BigDecimal customerId   ;
	@JsonProperty("Insuredaddressdifferent")
    private String     insuredAddressDifferent ;
	@JsonProperty("Address1")
    private String     address1     ;
	@JsonProperty("Pobox")
    private String     pobox        ;
	@JsonProperty("Country")
    private String     country      ;
	@JsonProperty("Emirate")
    private String     emirate      ;
	@JsonProperty("Freezone")
    private BigDecimal freezone     ;
	@JsonProperty("Contentvalue")
    private BigDecimal contentValue ;
	@JsonProperty("Contentvalueothers")
    private BigDecimal contentValueOthers ;
	@JsonProperty("Claimstatus")
    private String     claimStatus  ;
	@JsonProperty("Lastyears1")
    private BigDecimal lastYears1   ;
	@JsonProperty("Lastyears2")
    private BigDecimal lastYears2   ;
	@JsonProperty("Lastyears3")
    private BigDecimal lastYears3   ;
	@JsonProperty("Amount1")
    private BigDecimal amount1      ;
	@JsonProperty("Amount2")
    private BigDecimal amount2      ;
	@JsonProperty("Amount3")
    private BigDecimal amount3      ;
	@JsonFormat(pattern = "dd/MM/yyyy")
	@JsonProperty("Inceptiondate")
    private Date       inceptionDate ;
	@JsonFormat(pattern = "dd/MM/yyyy")
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Applicationno")
    private BigDecimal applicationNo ;
	@JsonProperty("Remarks")
    private String     remarks      ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Specialcondition")
    private String     specialCondition ;
	@JsonProperty("Activityprofession")
    private BigDecimal activityProfession ;
	@JsonProperty("Activitystatus")
    private String     activityStatus ;
	@JsonFormat(pattern = "dd/MM/yyyy")
	@JsonProperty("Expirydate")
    private Date       expiryDate   ;
	@JsonProperty("Profothers")
    private String     profOthers   ;
	@JsonProperty("Freezoneothers")
    private String     freezoneOthers ;
	@JsonProperty("Contentstatus")
    private String     contentStatus ;
	@JsonProperty("Noofclaim1")
    private BigDecimal noOfClaim1   ;
	@JsonProperty("Noofclaim2")
    private BigDecimal noOfClaim2   ;
	@JsonProperty("Noofclaim3")
    private BigDecimal noOfClaim3   ;
	@JsonProperty("Telephone")
    private String     telephone    ;
	@JsonProperty("Email")
    private String     email        ;
	@JsonProperty("Contenttypeid")
    private BigDecimal contentTypeId ;
	@JsonProperty("Pacoveryn")
    private String     pacoverYn    ;
	@JsonProperty("Tracteryn")
    private String     tracterYn    ;
	@JsonProperty("Referralremarks")
    private String     referralRemarks ;
	@JsonProperty("Actualpremium")
    private BigDecimal actualPremium ;
	@JsonProperty("Discountpremium")
    private BigDecimal discountPremium ;
	@JsonProperty("Actualoppremium")
    private BigDecimal actualOppremium ;
	@JsonProperty("Discountpercent")
    private BigDecimal discountPercent ;
	@JsonProperty("Nametitle")
    private String     nameTitle    ;
	@JsonProperty("Firstname")
    private String     firstName    ;
	@JsonProperty("Lastname")
    private String     lastName     ;
	@JsonProperty("Customertype")
    private String     cusTypeDesc ;
	@JsonProperty("Noofdays")
    private BigDecimal noOfDays     ;
	@JsonProperty("Loginid")
    private String     loginId      ;
	@JsonProperty("Applicationid")
    private String     applicationId ;
	@JsonProperty("BranchCode")
	private String     branchcode;
	@JsonProperty("EndDateId")
	private String     endDateId ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
