/*
 * Java domain class for entity "OfsDataDetails" 
 * Created on 2022-01-19 ( Date ISO 2022-01-19 - Time 12:54:42 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;

import lombok.*;
import java.math.BigDecimal;
import java.util.Date;


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * Domain class for entity "OfsDataDetails"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class OfsDataDetailsDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Quoteno")
    private BigDecimal quoteNo      ;
	@JsonProperty("Coveragesid")
    private BigDecimal coveragesId  ;
	@JsonProperty("Productid")
    private BigDecimal productId    ;
	@JsonProperty("Schemeid")
    private BigDecimal schemeId     ;
	@JsonProperty("Locationid")
    private BigDecimal locationId   ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Amendid")
    private BigDecimal amendId      ;
	@JsonProperty("Coveragessuminsured")
    private String     coveragesSuminsured ;
	@JsonProperty("Premiumamount")
    private BigDecimal premiumAmount ;
	@JsonProperty("Remarks")
    private String     remarks      ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Coveragesynoption")
    private String     coveragesYNOption ;
	@JsonProperty("Contenttypeid")
    private BigDecimal contentTypeId ;
	@JsonProperty("Coveragesbaserate")
    private BigDecimal coveragesBaseRate ;
	@JsonProperty("Calculatedsi")
    private BigDecimal calculatedSi ;
	@JsonProperty("Adjustamount")
    private BigDecimal adjustAmount ;
	@JsonProperty("Referralremarks")
    private String     referralRemarks ;
	@JsonProperty("Coveragetext")
    private String     coverageText ;
	@JsonProperty("Coveragedate")
    private Date       coverageDate ;
	@JsonProperty("Coveragecheck")
    private String     coverageCheck ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Fieldname")
    private String     fieldName    ;
	@JsonProperty("Moduleid")
    private BigDecimal moduleId     ;
	@JsonProperty("Screenid")
    private BigDecimal screenId     ;
	@JsonProperty("Subscreenid")
    private BigDecimal subscreenId  ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
