/*
 * Java domain class for entity "OfsTransactionDetails" 
 * Created on 2022-01-22 ( Date ISO 2022-01-22 - Time 18:25:35 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;

import lombok.*;
import java.math.BigDecimal;
import java.util.Date;


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * Domain class for entity "OfsTransactionDetails"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class OfsTransactionDetailsDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Quoteno")
    private BigDecimal quoteNo      ;
	@JsonProperty("Productid")
    private BigDecimal productId    ;
	@JsonProperty("Schemeid")
    private BigDecimal schemeId     ;
	@JsonProperty("Coveragesid")
    private BigDecimal coveragesId  ;
	@JsonProperty("Coveragessubid")
    private BigDecimal coveragesSubId ;
	@JsonProperty("Locationid")
    private BigDecimal locationId   ;
	@JsonProperty("Moduleid")
    private BigDecimal moduleId     ;
	@JsonProperty("Screenid")
    private BigDecimal screenId     ;
	@JsonProperty("Subscreenid")
    private BigDecimal subscreenId  ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Contenttypeid")
    private BigDecimal contentTypeId ;
	@JsonProperty("Moredetailsid")
    private BigDecimal moreDetailsId ;
	@JsonProperty("Field1")
    private BigDecimal field1       ;
	@JsonProperty("Field2")
    private BigDecimal field2       ;
	@JsonProperty("Field3")
    private BigDecimal field3       ;
	@JsonProperty("Field4")
    private BigDecimal field4       ;
	@JsonProperty("Field5")
    private String     field5       ;
	@JsonProperty("Field6")
    private String     field6       ;
	@JsonProperty("Field7")
    private String     field7       ;
	@JsonProperty("Field8")
    private String     field8       ;
	@JsonProperty("Field9")
    private String     field9       ;
	@JsonProperty("Field10")
    private String     field10      ;
	@JsonProperty("Field11")
    private String     field11      ;
	@JsonProperty("Field12")
    private String     field12      ;
	@JsonProperty("Field13")
    private Date       field13      ;
	@JsonProperty("Field14")
    private Date       field14      ;
	@JsonProperty("Field15")
    private Date       field15      ;
	@JsonProperty("Amendid")
    private BigDecimal amendId      ;
	@JsonProperty("Status")
    private String     status       ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
