/*
 * Java domain class for entity "PolicytypeMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.maan.common.bean.BrokerCommissionMaster;
import com.maan.common.bean.ProductMaster;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "PolicytypeMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class PolicytypeMasterDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Policytypeid")
    private BigDecimal policytypeId ;
	@JsonProperty("Productid")
    private BigDecimal productId    ;
	@JsonProperty("Inscompanyid")
    private BigDecimal insCompanyId ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Policytypename")
    private String     policytypeName ;
	@JsonProperty("Policytypedescenglish")
    private String     policytypeDescEnglish ;
	@JsonProperty("Policytypedescarabic")
    private String     policytypeDescArabic ;
	@JsonProperty("Policyprefix")
    private String     policyPrefix ;
	@JsonProperty("Quotetype")
    private String     quotetype    ;
	@JsonProperty("Coreappcode")
    private String     coreAppcode  ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Expirydate")
    private Date       expiryDate   ;
	@JsonProperty("Remarks")
    private String     remarks      ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@JsonProperty("Listofbrokercommissionmaster")
    private List<BrokerCommissionMaster> listOfBrokerCommissionMaster ;
	@JsonProperty("Productmaster")
    private ProductMaster productMaster ;

      
	  
	  
}
