/*
 * Java domain class for entity "ProductMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.maan.common.bean.PolicytypeMaster;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "ProductMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class ProductMasterDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Productid")
    private BigDecimal productId    ;
	@JsonProperty("Inscompanyid")
    private BigDecimal insCompanyId ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Productname")
    private String     productName  ;
	@JsonProperty("Productcode")
    private String     productCode  ;
	@JsonProperty("Coreappcode")
    private String     coreAppcode  ;
	@JsonProperty("Branchcode")
    private String     branchCode   ;
	@JsonProperty("Displayorder")
    private BigDecimal displayOrder ;
	@JsonProperty("Paymentyn")
    private String     paymentYn    ;
	@JsonProperty("Paymentredirurl")
    private String     paymentRedirUrl ;
	@JsonProperty("Apploginurl")
    private String     appLoginUrl  ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Expirydate")
    private Date       expiryDate   ;
	@JsonProperty("Remarks")
    private String     remarks      ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@JsonProperty("Listofpolicytypemaster")
    private List<PolicytypeMaster> listOfPolicytypeMaster ;

      
	  
	  
}
