/*
 * Java domain class for entity "SessionDetails" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.domain;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "SessionDetails"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class SessionDetailsDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Loginid")
    private String     loginId      ;
	@JsonProperty("Tokenid")
    private String     tokenId      ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Branchcode")
    private String     branchCode   ;
	@JsonProperty("Branchname")
    private String     branchName   ;
	@JsonProperty("Usertype")
    private String     usertype     ;
	@JsonProperty("Productid")
    private String     productId    ;
	@JsonProperty("Opencoverno")
    private String     opencoverNo  ;
	@JsonProperty("Countryid")
    private String     countryId    ;
	@JsonProperty("Agencycode")
    private String     agencyCode   ;
	@JsonProperty("Temptokenid")
    private String     tempTokenid  ;
	@JsonProperty("Currencyname")
    private String     currencyName ;
	@JsonProperty("Menuid")
    private String     menuId       ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Regioncode")
    private String     regionCode   ;
	@JsonProperty("Apilink")
    private String     apiLink      ;
	@JsonProperty("Sessionid")
    private String     sessionId    ;
	@JsonProperty("Starttime")
    private Date       startTime    ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Sysipaddress")
    private String     sysIpAddress ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
