/*
 * Java domain class for entity "NotifTemplateMaster" 
 * Created on 2021-11-19 ( Date ISO 2021-11-19 - Time 13:16:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.master.request;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "NotifTemplateMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class NotifTemplateMasterReq implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Sno")
    private BigDecimal sno          ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("InsuranceId")
    private BigDecimal insId        ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Mailrequired")
    private String     mailRequired ;
	@JsonProperty("Mailsubject")
    private String     mailSubject  ;
	@JsonProperty("Mailbody")
    private String     mailBody     ;
	@JsonProperty("Mailregards")
    private String     mailRegards  ;
	@JsonProperty("Smsrequired")
    private String     smsRequired  ;
	@JsonProperty("Smssubject")
    private String     smsSubject   ;
	@JsonProperty("Smsbodyen")
    private String     smsBodyEn    ;
	@JsonProperty("Smsbodyar")
    private String     smsBodyAr    ;
	@JsonProperty("Smsregards")
    private String     smsRegards   ;
	@JsonFormat(pattern = "dd/MM/yyyy")
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Remarks")
    private String     remarks      ;
	@JsonProperty("Emailto")
    private String     emailTo      ;
	@JsonProperty("Emailcc")
    private String     emailCc      ;
	@JsonProperty("Usertype")
    private String     userType     ;
	@JsonProperty("Smsto")
    private String     smsTo        ;
	@JsonProperty("Smsregardsar")
    private String     smsRegardsAr ;
	@JsonProperty("Productid")
    private BigDecimal productId    ;
	@JsonProperty("Whatsapprequired")
    private String     whatsappRequired ;
	@JsonProperty("Mailbodyar")
    private String     mailBodyAr   ;
	@JsonProperty("Mailregardsar")
    private String     mailRegardsAr ;
	@JsonProperty("Fileyn")
    private String     fileYn       ;
	@JsonProperty("Shortremarks")
    private String     shortRemarks ;
	@JsonProperty("Hittype")
    private String     hitType      ;
	@JsonProperty("Whatsappsubject")
    private String     whatsappSubject ;
	@JsonProperty("Whatsappbodyen")
    private String     whatsappBodyEn ;
	@JsonProperty("Whatsappbodyar")
    private String     whatsappBodyAr ;
	@JsonProperty("Whatsappregards")
    private String     whatsappRegards ;
	@JsonProperty("Whatsappregardsar")
    private String     whatsappRegardsAr ;
	@JsonProperty("Querykey")
    private String     queryKey     ;
	@JsonFormat(pattern = "dd/MM/yyyy")
	@JsonProperty("Effectivedate")
    private Date       effectiveDate    ;
	@JsonProperty("Amendid")
	private BigDecimal amendid ;	  
}
