/*
 * Java domain class for entity "LoginMaster" 
 * Created on 2021-09-21 ( Date ISO 2021-09-21 - Time 16:37:37 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.upload.response;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "LoginMaster"
 *
 * @author Telosys Tools Generator
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class LoginMasterResDto {

	@JsonProperty("Usertype")
	private String usertype;
	@JsonProperty("Loginid")
	private String loginId;

}
