/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:36 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "BrokerCompanyMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(BrokerCompanyMasterId.class)
@Table(name="BROKER_COMPANY_MASTER")


public class BrokerCompanyMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="AGENCY_CODE", nullable=false, length=25)
    private String     agencyCode ;

    @Id
    @Column(name="INS_COMPANY_ID", nullable=false)
    private BigDecimal insCompanyId ;

    @Id
    @Column(name="BROKER_CODE", nullable=false, length=25)
    private String     brokerCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="COMPANY_NAME", length=75)
    private String     companyName ;

    @Column(name="CONTACT_PERSON", length=75)
    private String     contactPerson ;

    @Column(name="ADDRESS1", length=50)
    private String     address1 ;

    @Column(name="ADDRESS2", length=50)
    private String     address2 ;

    @Column(name="ADDRESS3", length=50)
    private String     address3 ;

    @Column(name="CITY", length=25)
    private String     city ;

    @Column(name="COUNTRY", length=25)
    private String     country ;

    @Column(name="PHONE", length=15)
    private String     phone ;

    @Column(name="POBOX")
    private BigDecimal pobox ;

    @Column(name="FAX", length=50)
    private String     fax ;

    @Column(name="CUSTOMER_ID")
    private BigDecimal customerId ;

    @Column(name="BRANCH_CODE", length=8)
    private String     branchCode ;

    @Column(name="AC_EXECUTIVE_ID")
    private BigDecimal acExecutiveId ;

    @Column(name="BROKER_TYPE", length=10)
    private String     brokerType ;

    @Column(name="SOURCE_CODE", length=10)
    private String     sourceCode ;

    @Column(name="SOURCE_TYPE", length=10)
    private String     sourceType ;

    @Column(name="MODEOFPAY", length=10)
    private String     modeofpay ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="REMARKS", length=300)
    private String     remarks ;
    @Column(name="RSA_BROKER_CODE", length=25)
    private String     rsabrokerCode ;
    

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="AGENCY_CODE", referencedColumnName="AGENCY_CODE", insertable=false, updatable=false)
    private BrokerMaster brokerMaster ; 



}



