/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:37 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "BrokerPaymentDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(BrokerPaymentDetailId.class)
@Table(name="BROKER_PAYMENT_DETAIL")


public class BrokerPaymentDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="USERTYPE", nullable=false, length=50)
    private String     usertype ;

    @Id
    @Column(name="CUSTOMER_CODE", nullable=false, length=200)
    private String     customerCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CUSTOMER_TYPE", nullable=false, length=50)
    private String     customerType ;

    @Column(name="AMEND_ID")
    private BigDecimal amendId ;

    @Column(name="CREDIT", length=50)
    private String     credit ;

    @Column(name="CASH", length=50)
    private String     cash ;

    @Column(name="POS", length=50)
    private String     pos ;

    @Column(name="ONLINE_PAYMENT", length=50)
    private String     onlinePayment ;

    @Column(name="CHEQUE", length=50)
    private String     cheque ;

    @Column(name="BANK_TRANSFER", length=50)
    private String     bankTransfer ;

    @Column(name="AIRTEL_MONEY", length=50)
    private String     airtelMoney ;

    @Column(name="MTN_MONEY", length=50)
    private String     mtnMoney ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=10)
    private String     status ;

    @Column(name="REMARKS", length=50)
    private String     remarks ;

    @Column(name="PAYMENT_ID")
    private BigDecimal paymentId ;

    @Column(name="CASH_MAX_LIMIT")
    private BigDecimal cashMaxLimit ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



