/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-01-29 ( Date ISO 2022-01-29 - Time 17:21:02 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-01-29 ( 17:21:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "BrokerBranchMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(BrokerBranchMasterId.class)
@Table(name="BROKER_BRANCH_MASTER")


public class BrokerBranchMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="BROKER_ID", nullable=false, length=15)
    private String     brokerId ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=10)
    private String     branchCode ;

    @Id
    @Column(name="MGEN_BRANCH_ID", nullable=false, length=8)
    private String     mgenBranchId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SNO")
    private BigDecimal sno ;

    @Column(name="BRANCH_ID")
    private BigDecimal branchId ;

    @Column(name="BRANCH_NAME", length=100)
    private String     branchName ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date entryDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE")
    private Date     effectiveDate ;

    //--- ENTITY LINKS ( RELATIONSHIP )


}



