/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:36 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "BrokerCommissionMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(BrokerCommissionMasterId.class)
@Table(name="BROKER_COMMISSION_MASTER")


public class BrokerCommissionMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="AGENCY_CODE", nullable=false, length=50)
    private String     agencyCode ;

    @Id
    @Column(name="INS_COMPANY_ID", nullable=false)
    private BigDecimal insCompanyId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Column(name="POLICYTYPE_ID", nullable=false)
    private BigDecimal policytypeId ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SUMINSURED_START")
    private BigDecimal suminsuredStart ;

    @Column(name="SUMINSURED_END")
    private BigDecimal suminsuredEnd ;

    @Column(name="COMMISSION_PERCENTAGE")
    private BigDecimal commissionPercentage ;

    @Column(name="CHECKER_YN", length=10)
    private String     checkerYn ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE")
    private Date       endDate ;

    @Column(name="OTHER_FEE_1")
    private BigDecimal otherFee1 ;

    @Column(name="OTHER_FEE_2")
    private BigDecimal otherFee2 ;

    @Column(name="OTHER_FEE_3")
    private BigDecimal otherFee3 ;

    @Column(name="VATPERCENT")
    private BigDecimal vatpercent ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumns( { 
        @JoinColumn(name="POLICYTYPE_ID", referencedColumnName="POLICYTYPE_ID", insertable=false, updatable=false),
        @JoinColumn(name="PRODUCT_ID", referencedColumnName="PRODUCT_ID", insertable=false, updatable=false),
        @JoinColumn(name="INS_COMPANY_ID", referencedColumnName="INS_COMPANY_ID", insertable=false, updatable=false) } )
    private PolicytypeMaster policytypeMaster ; 

    @ManyToOne
    @JoinColumn(name="AGENCY_CODE", referencedColumnName="AGENCY_CODE", insertable=false, updatable=false)
    private BrokerMaster brokerMaster ; 



}



