/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:37 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.*;




/**
* Domain class for entity "BrokerMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="BROKER_MASTER")


public class BrokerMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="AGENCY_CODE", nullable=false, length=25)
    private String     agencyCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="BRANCH_CODE", length=8)
    private String     branchCode ;

    @Column(name="POLICY_FEE_STATUS", length=1)
    private String     policyFeeStatus ;

    @Column(name="TAX_STATUS", length=1)
    private String     taxStatus ;

    @Column(name="VAT_STATUS", length=1)
    private String     vatStatus ;

    @Column(name="POLICY_FEE")
    private BigDecimal policyFee ;

    @Column(name="TAX")
    private BigDecimal tax ;

    @Column(name="VAT")
    private BigDecimal vat ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRY_DATE")
    private Date       expiryDate ;

    @Column(name="REMARKS", length=300)
    private String     remarks ;

    @Column(name="INS_COMPANY_ID")
    private BigDecimal insCompanyId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="brokerMaster")
    private List<BrokerCompanyMaster> listOfBrokerCompanyMaster ; 

    @OneToMany(mappedBy="brokerMaster")
    private List<BrokerCommissionMaster> listOfBrokerCommissionMaster ; 



}



