/*
 * Created on 2021-11-19 ( 13:16:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.common.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "CityMaster" ( stored in table "CITY_MASTER" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
public class CityMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     cityCode ;
    
    private String     bankCode ;
    
     
}
