/*
 * Created on 2022-02-11 ( 19:14:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.common.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;
import java.util.Date;

/**
 * Composite primary key for entity "ClaimDocumentMaster" ( stored in table "CLAIM_DOCUMENT_MASTER" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class ClaimDocumentMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private BigDecimal documentId ;
    
    private String     docApplicable ;
    
    private BigDecimal productId ;
    
    private Date       effectiveDate ;
    
    private BigDecimal amendId ;
    
    private BigDecimal companyId ;
    
     
}
