/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:38 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "ClaimDocumentMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(ClaimDocumentMasterId.class)
@Table(name="CLAIM_DOCUMENT_MASTER")


public class ClaimDocumentMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="DOCUMENT_ID", nullable=false)
    private BigDecimal documentId ;

    @Id
    @Column(name="DOC_APPLICABLE", nullable=false, length=100)
    private String     docApplicable ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE", nullable=false)
    private Date       effectiveDate ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    @Id
    @Column(name="COMPANY_ID", nullable=false)
    private BigDecimal companyId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="DOCUMENT_DESC", length=100)
    private String     documentDesc ;

    @Column(name="POLICY_TYPE", length=100)
    private String     policyType ;

    @Column(name="MANDATORY_STATUS", length=1)
    private String     mandatoryStatus ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="DISPLAY_ORDER")
    private BigDecimal displayOrder ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="DOCUMENT_DESC_ARABIC", length=1000)
    private String     documentDescArabic ;

    @Column(name="API_CHECK", length=10)
    private String     apiCheck ;

    @Column(name="API_CHECK_NAME", length=100)
    private String     apiCheckName ;

    @Column(name="CORE_APPCODE", length=10)
    private String     coreAppcode ;

    @Column(name="AGENCY_CODE", length=20)
    private String     agencyCode ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="COMPANY_ID", referencedColumnName="INS_ID", insertable=false, updatable=false)
    private InsuranceCompanyMaster insuranceCompanyMaster ; 

    @ManyToOne
    @JoinColumns( { 
        @JoinColumn(name="PRODUCT_ID", referencedColumnName="PRODUCT_ID", insertable=false, updatable=false),
        @JoinColumn(name="COMPANY_ID", referencedColumnName="INS_COMPANY_ID", insertable=false, updatable=false) } )
    private ProductMaster productMaster ; 



}



