/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:38 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "CoverageMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="COVERAGE_MASTER")


public class CoverageMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="MC_COVERID", nullable=false)
    private BigDecimal mcCoverid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="MC_FIELDNAME", length=100)
    private String     mcFieldname ;

    @Column(name="MC_FIELDLABELNAME", length=150)
    private String     mcFieldlabelname ;

    @Column(name="MC_INPUTFIELD", length=20)
    private String     mcInputfield ;

    @Column(name="MC_OPTIONS", length=1000)
    private String     mcOptions ;

    @Column(name="MC_DATATYPE", length=20)
    private String     mcDatatype ;

    @Column(name="MC_LENGTH")
    private BigDecimal mcLength ;

    @Column(name="MC_MANDATORY", length=5)
    private String     mcMandatory ;

    @Column(name="MC_DATETYPEFORMAT", length=20)
    private String     mcDatetypeformat ;

    @Column(name="MC_VALIDATIONMESSAGE", length=2000)
    private String     mcValidationmessage ;

    @Column(name="MC_PARENTID")
    private BigDecimal mcParentid ;

    @Column(name="MC_APIURL", length=100)
    private String     mcApiurl ;

    @Column(name="MC_VALUE", length=100)
    private String     mcValue ;

    @Column(name="MC_PARENTNAME", length=100)
    private String     mcParentname ;

    @Column(name="MC_CHILDNAME", length=100)
    private String     mcChildname ;

    @Column(name="MC_CASCADINGOPTIONS", length=1000)
    private String     mcCascadingoptions ;

    @Column(name="MC_STATUS", length=20)
    private String     mcStatus ;

    @Temporal(TemporalType.DATE)
    @Column(name="MC_ENTRYDATE")
    private Date       mcEntrydate ;

    @Column(name="MC_SEQUENCEYN", length=1)
    private String     mcSequenceyn ;

    @Column(name="MC_DISPLAY_ORDER", length=100)
    private String     mcDisplayOrder ;

    @Column(name="MC_REQUESTTYPE", length=1000)
    private String     mcRequesttype ;

    @Column(name="MC_REQUESTKEYS", length=1000)
    private String     mcRequestkeys ;

    @Column(name="MC_REQUESTVALUES", length=1000)
    private String     mcRequestvalues ;

    @Column(name="TOOLTIP_MES", length=1000)
    private String     tooltipMes ;

    @Column(name="COVERAGETYPE", length=10)
    private String     coveragetype ;

    @Column(name="UPLOADOPTION", length=10)
    private String     uploadoption ;

    @Column(name="MAXSUMINSURED")
    private BigDecimal maxsuminsured ;

    @Column(name="COVERAGELIMIT")
    private BigDecimal coveragelimit ;

    @Column(name="CALCTYPE", length=10)
    private String     calctype ;

    @Column(name="CALCSTATUS", length=10)
    private String     calcstatus ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVEDATE")
    private Date       effectivedate ;

    @Column(name="CORECODE", length=10)
    private String     corecode ;

    @Column(name="MC_OPTIONKEYS", length=10)
    private String     mcOptionkeys ;

    @Column(name="MC_OPTIONVALUES", length=10)
    private String     mcOptionvalues ;

    @Column(name="BASE_RATE", length=100)
    private String     baseRate ;

    @Column(name="CALC_YN", length=100)
    private String     calcYn ;

    @Column(name="EXCESS", length=100)
    private String     excess ;

    @Column(name="MIN_PREMIUM", length=50)
    private String     minPremium ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



