/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:39 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:39 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "DocumentUploadDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(DocumentUploadDetailsId.class)
@Table(name="DOCUMENT_UPLOAD_DETAILS")


public class DocumentUploadDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="CLAIM_NO", nullable=false, length=100)
    private String     claimNo ;

    @Id
    @Column(name="DOCUMENT_REF", nullable=false)
    private BigDecimal documentRef ;

    @Id
    @Column(name="DOC_TYPE_ID", nullable=false, length=10)
    private String     docTypeId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Column(name="PARAM", nullable=false, length=4000)
    private String     param ;

    @Id
    @Column(name="INS_ID", nullable=false)
    private BigDecimal insId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="FILE_PATH_NAME", length=2000)
    private String     filePathName ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPLOADED_TIME")
    private Date       uploadedTime ;

    @Column(name="DESCRIPTION", length=200)
    private String     description ;

    @Column(name="STATUS", length=20)
    private String     status ;

    @Column(name="FILE_NAME", length=500)
    private String     fileName ;

    @Column(name="VTYPE_ID", length=50)
    private String     vtypeId ;

    @Column(name="OP_STATUS", length=10)
    private String     opStatus ;

    @Column(name="OP_REMARKS", length=1000)
    private String     opRemarks ;

    @Column(name="UPLOAD_TYPE", length=100)
    private String     uploadType ;

    @Column(name="DOC_ID", length=1000)
    private String     docId ;

    @Column(name="PARAM2", length=4000)
    private String     param2 ;

    @Column(name="PARAM3", length=4000)
    private String     param3 ;

    @Column(name="DETECT", length=4000)
    private String     detect ;

    @Column(name="COMMON_FILE_PATH", length=2000)
    private String     commonFilePath ;

    @Column(name="ERROR_RES", length=4000)
    private String     errorRes ;

    @Column(name="DETECT_PERC")
    private BigDecimal detectPerc ;

    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    @Column(name="CREATEDBY", length=100)
    private String     createdby ;

    @Column(name="PARTY_NO", length=100)
    private String     partyNo ;

    @Column(name="LOSS_ID", length=200)
    private String     lossId ;

    @Column(name="WAIVEOFF_YN", length=2)
    private String     waiveoffYn ;

    @Column(name="REMARKS", length=200)
    private String     remarks ;

    @Temporal(TemporalType.DATE)
    @Column(name="WAIVEOFFDATE")
    private Date       waiveoffdate ;

    @Column(name="WAIVEOFFBY", length=200)
    private String     waiveoffby ;

    @Column(name="WAIVEOFFCLAIMREMARKS", length=200)
    private String     waiveoffclaimremarks ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



