/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:39 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:39 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "EserviceVehicleDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(EserviceVehicleDetailId.class)
@Table(name="ESERVICE_VEHICLE_DETAIL")


public class EserviceVehicleDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="VEHICLE_REFERENCENO", nullable=false)
    private String vehicleReferenceno ;

    @Id
    @Column(name="VEHICLE_ID", nullable=false)
    private BigDecimal vehicleId ;

    @Id
    @Column(name="CUSTOMER_ID", nullable=false)
    private BigDecimal customerId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CHASSIS_NO", length=50)
    private String     chassisNo ;

    @Column(name="PLATE_NO", length=100)
    private String     plateNo ;

    @Column(name="PLATE_CHAR", length=100)
    private String     plateChar ;

    @Column(name="PLATECHAR_EN", length=100)
    private String     platecharEn ;

    @Column(name="MAKE_ID")
    private BigDecimal makeId ;

    @Column(name="MAKE_NAME", length=60)
    private String     makeName ;

    @Column(name="VEHICLE_MODEL")
    private BigDecimal vehicleModel ;

    @Column(name="MODEL_NAME", length=60)
    private String     modelName ;

    @Column(name="VEHICLE_BODYTYPE_ID")
    private BigDecimal vehicleBodytypeId ;

    @Column(name="VEHICLE_BODYTYPE_NAME", length=60)
    private String     vehicleBodytypeName ;

    @Column(name="VEHILCE_COLORID")
    private BigDecimal vehilceColorid ;

    @Column(name="VEHICLE_COLOR", length=60)
    private String     vehicleColor ;

    @Column(name="SEATING_CAPACITY")
    private BigDecimal seatingCapacity ;

    @Column(name="ENGINE_CAPACITY")
    private BigDecimal engineCapacity ;

    @Column(name="MANFYEAR")
    private BigDecimal manfyear ;

    @Column(name="ENGINE_NO", length=60)
    private String     engineNo ;

    @Column(name="VEHAGE")
    private BigDecimal vehage ;

    @Column(name="CLAIMAMT")
    private BigDecimal claimamt ;

    @Column(name="CLAIMBONUS")
    private BigDecimal claimbonus ;

    @Column(name="VEHUSAGE_ID")
    private BigDecimal vehusageId ;

    @Column(name="STATUS", length=5)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRYDATE")
    private Date       entrydate ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="CIVILID", length=100)
    private String     civilid ;

    @Temporal(TemporalType.DATE)
    @Column(name="POLICY_STARTDATE")
    private Date       policyStartdate ;

    @Column(name="LEASEDYN", length=1)
    private String     leasedyn ;

    @Column(name="SUM_INSURED")
    private BigDecimal sumInsured ;

    @Column(name="ELECTRICAL_SI")
    private BigDecimal electricalSi ;

    @Column(name="NONELECTRICAL_SI")
    private BigDecimal nonelectricalSi ;

    @Column(name="EXCESS_LIMIT")
    private BigDecimal excessLimit ;

    @Column(name="REGISTRATION_NO", length=60)
    private String     registrationNo ;

    @Column(name="VEHICLE_VALUE")
    private BigDecimal vehicleValue ;

    @Column(name="BANK_OF_FINANCE", length=70)
    private String     bankOfFinance ;

    @Column(name="VEHICLE_USAGE", length=30)
    private String     vehicleUsage ;

    @Column(name="DRIVER_ID", length=30)
    private String     driverId ;

    @Temporal(TemporalType.DATE)
    @Column(name="DRIVER_DOB")
    private Date       driverDob ;

    @Column(name="DRIVER_CLAIM_DETAILYN", length=3)
    private String     driverClaimDetailyn ;

    @Column(name="PAST_CLAIM_YN", length=3)
    private String     pastClaimYn ;

    @Column(name="CLAIM_FREE_YEARS", length=10)
    private String     claimFreeYears ;

    @Column(name="CLAIM_AMOUNT")
    private BigDecimal claimAmount ;

    @Column(name="OLD_POLICYNO")
    private BigDecimal oldPolicyno ;

    @Temporal(TemporalType.DATE)
    @Column(name="OLD_POLICY_EXPIRYDATE")
    private Date       oldPolicyExpirydate ;

    @Column(name="OLD_POLICY_INSURANCE_COMPANY", length=30)
    private String     oldPolicyInsuranceCompany ;

    @Column(name="VEHICLEOWNER_YN", length=3)
    private String     vehicleownerYn ;

    @Column(name="BANK_ID")
    private BigDecimal bankId ;

    @Column(name="OLD_POLICY_COMPANYID")
    private BigDecimal oldPolicyCompanyid ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumns( { 
        @JoinColumn(name="VEHICLE_REFERENCENO", referencedColumnName="REQUESTREFERENCENO", insertable=false, updatable=false),
        @JoinColumn(name="CUSTOMER_ID", referencedColumnName="CUSTOMER_ID", insertable=false, updatable=false) } )
    private EserviceRequestDetail eserviceRequestDetail ; 



}



