/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "HomePositionMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(HomePositionMasterId.class)
@Table(name="HOME_POSITION_MASTER")


public class HomePositionMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="QUOTE_NO", nullable=false)
    private BigDecimal quoteNo ;

    @Id
    @Column(name="CUSTOMER_ID", nullable=false)
    private BigDecimal customerId ;

    @Id
    @Column(name="LOGIN_ID", nullable=false, length=50)
    private String     loginId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Column(name="APPLICATION_NO", nullable=false)
    private BigDecimal applicationNo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="PROPOSAL_NO", length=15)
    private String     proposalNo ;

    @Column(name="COMPANY_ID")
    private BigDecimal companyId ;

    @Column(name="POLICY_NO", length=100)
    private String     policyNo ;

    @Column(name="POLICY_TERM", length=20)
    private String     policyTerm ;

    @Column(name="PREMIUM")
    private BigDecimal premium ;

    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INCEPTION_DATE")
    private Date       inceptionDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPIRY_DATE")
    private Date       expiryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="STATUS", length=3)
    private String     status ;

    @Column(name="DEBIT_NOTE_NO", length=25)
    private String     debitNoteNo ;

    @Temporal(TemporalType.DATE)
    @Column(name="DEBIT_NOTE_DATE")
    private Date       debitNoteDate ;

    @Column(name="LAPSED_REMARKS", length=250)
    private String     lapsedRemarks ;

    @Temporal(TemporalType.DATE)
    @Column(name="LAPSED_DATE")
    private Date       lapsedDate ;

    @Column(name="LAPSED_UPDATED_BY", length=50)
    private String     lapsedUpdatedBy ;

    @Column(name="PDF_BROKER_STATUS")
    private BigDecimal pdfBrokerStatus ;

    @Column(name="BROKER_ADDITIONAL_COMMISSION")
    private BigDecimal brokerAdditionalCommission ;

    @Column(name="NO_CLAIM_DISCOUNT", length=10)
    private String     noClaimDiscount ;

    @Column(name="NO_CLAIM_DISCOUNT_VALUE")
    private BigDecimal noClaimDiscountValue ;

    @Column(name="EXCESS_PREMIUM")
    private BigDecimal excessPremium ;

    @Column(name="ADMIN_REMARKS", length=470)
    private String     adminRemarks ;

    @Column(name="ADMIN_REFERRAL_STATUS", length=1)
    private String     adminReferralStatus ;

    @Column(name="EXCESS_SIGN", length=1)
    private String     excessSign ;

    @Column(name="OVERALL_PREMIUM")
    private BigDecimal overallPremium ;

    @Column(name="COMMISSION")
    private BigDecimal commission ;

    @Column(name="SUMMARY_CLAUSES", length=470)
    private String     summaryClauses ;

    @Column(name="SUMMARY_REMARKS", length=4000)
    private String     summaryRemarks ;

    @Column(name="REFERRAL_DESCRIPTION", length=500)
    private String     referralDescription ;

    @Column(name="ADMIN_SUMMARY_STATUS", length=1)
    private String     adminSummaryStatus ;

    @Column(name="BED_ROOM")
    private BigDecimal bedRoom ;

    @Column(name="AGE_ABOVE_SIXTY_FIVE", length=1)
    private String     ageAboveSixtyFive ;

    @Column(name="EXISTING_MEDICAL_CONDITION", length=1)
    private String     existingMedicalCondition ;

    @Column(name="MEDICAL_TRAVEL_CLAIMS", length=1)
    private String     medicalTravelClaims ;

    @Column(name="CANCELLED_REASON", length=200)
    private String     cancelledReason ;

    @Temporal(TemporalType.DATE)
    @Column(name="CANCELLED_DATE")
    private Date       cancelledDate ;

    @Column(name="CANCELLED_BY", length=20)
    private String     cancelledBy ;

    @Column(name="REISSUED_POLICY_NO", length=25)
    private String     reissuedPolicyNo ;

    @Column(name="REISSUED_QUOTE_NO")
    private BigDecimal reissuedQuoteNo ;

    @Column(name="AIRMILES_NO", length=25)
    private String     airmilesNo ;

    @Column(name="INSURANCE_DETAILS", length=70)
    private String     insuranceDetails ;

    @Column(name="RECEIPT_NO", length=25)
    private String     receiptNo ;

    @Temporal(TemporalType.DATE)
    @Column(name="RECEIPT_DATE")
    private Date       receiptDate ;

    @Column(name="PAYMENT_MODE", length=20)
    private String     paymentMode ;

    @Column(name="SCHEME_ID")
    private BigDecimal schemeId ;

    @Column(name="CONTENT_TYPE_ID")
    private BigDecimal contentTypeId ;

    @Column(name="BTOC", length=25)
    private String     btoc ;

    @Column(name="DECLARATION_STATUS", length=10)
    private String     declarationStatus ;

    @Column(name="PAYMENT_STATUS", length=1)
    private String     paymentStatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="POLICY_DATE")
    private Date       policyDate ;

    @Column(name="APPROVED_BY", length=30)
    private String     approvedBy ;

    @Column(name="CSH_ID_TYP_CODE")
    private BigDecimal cshIdTypCode ;

    @Column(name="FLEET_INT_STATUS", length=10)
    private String     fleetIntStatus ;

    @Column(name="FLEET_NO", length=25)
    private String     fleetNo ;

    @Column(name="INGSERIAL_NUMBER", length=20)
    private String     ingserialNumber ;

    @Column(name="DISCOUNT_PREMIUM")
    private BigDecimal discountPremium ;

    @Column(name="COMMISSION_PERCENTAGE")
    private BigDecimal commissionPercentage ;

    @Column(name="CREDIT_NO", length=20)
    private String     creditNo ;

    @Temporal(TemporalType.DATE)
    @Column(name="CREDIT_DATE")
    private Date       creditDate ;

    @Column(name="COVER_NOTE_NUMBER")
    private BigDecimal coverNoteNumber ;

    @Column(name="APPLICATION_ID", length=50)
    private String     applicationId ;

    @Column(name="POLICY_FEE")
    private BigDecimal policyFee ;

    @Column(name="CLASS_ID", length=1)
    private String     classId ;

    @Column(name="BRANCH_CODE", length=8)
    private String     branchCode ;

    @Column(name="ENDT_TYPE_ID", length=100)
    private String     endtTypeId ;

    @Column(name="ORIGINAL_POLICY_NO", length=100)
    private String     originalPolicyNo ;

    @Column(name="ENDT_PREMIUM")
    private BigDecimal endtPremium ;

    @Column(name="ENDT_COMMISSION")
    private BigDecimal endtCommission ;

    @Column(name="CHQ_INV_NO", length=10)
    private String     chqInvNo ;

    @Column(name="BROKER_CODE", length=25)
    private String     brokerCode ;

    @Column(name="AC_EXECUTIVE_ID")
    private BigDecimal acExecutiveId ;

    @Column(name="TRAN_ID")
    private BigDecimal tranId ;

    @Column(name="ENDT_STATUS", length=10)
    private String     endtStatus ;

    @Column(name="QUATER_ID")
    private BigDecimal quaterId ;

    @Column(name="VEHICLE_ID")
    private BigDecimal vehicleId ;

    @Column(name="CURRENCY", length=50)
    private String     currency ;

    @Column(name="SMS_YN", length=5)
    private String     smsYn ;

    @Column(name="MIN_PREMIUM_YN", length=2)
    private String     minPremiumYn ;

    @Column(name="RENEWAL_STATUS", length=50)
    private String     renewalStatus ;

    @Column(name="RENEWAL_OLD_POLICY", length=100)
    private String     renewalOldPolicy ;

    @Column(name="RENEWAL_DATE_YN", length=1)
    private String     renewalDateYn ;

    @Column(name="INSTALLMENT_YN", length=20)
    private String     installmentYn ;

    @Column(name="ONLINE_DISCOUNT")
    private BigDecimal onlineDiscount ;

    @Column(name="POLICY_FEE_PERCENT")
    private BigDecimal policyFeePercent ;

    @Column(name="BROKER_BRANCH", length=100)
    private String     brokerBranch ;

    @Column(name="ACTUAL_PREMIUM")
    private BigDecimal actualPremium ;

    @Column(name="ACTUAL_OPPREMIUM")
    private BigDecimal actualOppremium ;

    @Column(name="VOLUME_DISCOUNT_AMOUNT")
    private BigDecimal volumeDiscountAmount ;

    @Column(name="CORPORATE_DISCOUNT_AMOUNT")
    private BigDecimal corporateDiscountAmount ;

    @Column(name="SPECIAL_DISCOUNT_AMOUNT")
    private BigDecimal specialDiscountAmount ;

    @Column(name="HIT_COUNT")
    private BigDecimal hitCount ;

    @Column(name="CUST_APPROVE_STATUS", length=1)
    private String     custApproveStatus ;

    @Column(name="CUST_REJECT_REMARKS", length=200)
    private String     custRejectRemarks ;

    @Temporal(TemporalType.DATE)
    @Column(name="CUST_APPROVE_DATE")
    private Date       custApproveDate ;

    @Column(name="INTEGRATION_ERROR", length=100)
    private String     integrationError ;

    @Column(name="INTEGRATION_STATUS", length=20)
    private String     integrationStatus ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



