/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:41 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.*;




/**
* Domain class for entity "InsuranceCompanyMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="INSURANCE_COMPANY_MASTER")


public class InsuranceCompanyMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="INS_ID", nullable=false)
    private BigDecimal insId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="INS_NAME", length=100)
    private String     insName ;

    @Column(name="INS_ADDRESS", length=300)
    private String     insAddress ;

    @Column(name="INS_COUNTRY")
    private BigDecimal insCountry ;

    @Column(name="INS_CITY")
    private BigDecimal insCity ;

    @Column(name="INS_ZIPCODE", length=10)
    private String     insZipcode ;

    @Column(name="INS_PHONE", length=60)
    private String     insPhone ;

    @Column(name="INS_EMAIL", length=100)
    private String     insEmail ;

    @Column(name="INS_WEBSITE", length=100)
    private String     insWebsite ;

    @Column(name="INS_IMAGE_LOGO", length=100)
    private String     insImageLogo ;

    @Column(name="INS_CORE_APPCODE", length=10)
    private String     insCoreAppcode ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRY_DATE")
    private Date       expiryDate ;

    @Column(name="REMARKS", length=300)
    private String     remarks ;

    @Column(name="INS_REGION_CODE", length=8)
    private String     insRegionCode ;

    @Column(name="LATITUE", length=20)
    private String     latitue ;

    @Column(name="LONGTITUE", length=20)
    private String     longtitue ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Column(name="AMENDID")
    private BigDecimal amendid ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="insuranceCompanyMaster")
    private List<LoginMaster> listOfLoginMaster ; 

    @OneToMany(mappedBy="insuranceCompanyMaster")
    private List<ClaimDocumentMaster> listOfClaimDocumentMaster ; 



}



