/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:41 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.*;




/**
* Domain class for entity "LoginMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(LoginMasterId.class)
@Table(name="LOGIN_MASTER")


public class LoginMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="LOGIN_ID", nullable=false, length=50)
    private String     loginId ;

    @Id
    @Column(name="USERTYPE", nullable=false, length=15)
    private String     usertype ;

    @Id
    @Column(name="AGENCY_CODE", nullable=false, length=100)
    private String     agencyCode ;

    @Id
    @Column(name="COMPANY_ID", nullable=false)
    private BigDecimal companyId ;

    @Id
    @Column(name="STATUS", nullable=false, length=1)
    private String     status ;

    @Id
    @Column(name="REGION_CODE", nullable=false, length=30)
    private String     regionCode ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=20)
    private String     branchCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="PASSWORD", length=100)
    private String     password ;

    @Column(name="USERNAME", length=100)
    private String     username ;

    @Column(name="USERID")
    private BigDecimal userid ;

    @Column(name="OA_CODE", length=100)
    private String     oaCode ;

    @Column(name="ACCESSTYPE", length=15)
    private String     accesstype ;

    @Column(name="RIGHTS", length=100)
    private String     rights ;

    @Column(name="LPASS1", length=50)
    private String     lpass1 ;

    @Column(name="LPASS2", length=50)
    private String     lpass2 ;

    @Column(name="LPASS3", length=50)
    private String     lpass3 ;

    @Temporal(TemporalType.DATE)
    @Column(name="PASSDATE")
    private Date       passdate ;

    @Column(name="CREATED_BY", length=30)
    private String     createdBy ;

    @Column(name="USER_ID_CREATION", length=1)
    private String     userIdCreation ;

    @Column(name="AC_EXECUTIVE_CREATION", length=1)
    private String     acExecutiveCreation ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="REFERAL", length=25)
    private String     referal ;

    @Column(name="STATE_CODE", length=8)
    private String     stateCode ;

    @Column(name="COUNTRY_ID")
    private BigDecimal countryId ;

    @Column(name="LPASS4", length=50)
    private String     lpass4 ;

    @Column(name="LPASS5", length=50)
    private String     lpass5 ;

    @Column(name="MENU_ID", length=2000)
    private String     menuId ;

    @Column(name="PRODUCT_ID", length=100)
    private String     productId ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="INCEPTION_DATE")
    private Date       inceptionDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRY_DATE")
    private Date       expiryDate ;

    @Column(name="BROKER_CODES", length=2000)
    private String     brokerCodes ;

    @Column(name="FD_CODE", length=25)
    private String     fdCode ;

    @Column(name="CORE_LOGIN_ID", nullable=false, length=12)
    private String     coreLoginId ;

    @Column(name="APP_ID", length=50)
    private String     appId ;

    @Column(name="PWD_COUNT", length=50)
    private String     pwdCount ;

    @Column(name="USER_MAIL", length=50)
    private String     userMail ;

    @Column(name="ATTACHED_UW", length=200)
    private String     attachedUw ;

    @Column(name="ATTACHED_BRANCH", length=100)
    private String     attachedBranch ;

    @Column(name="RESTICT_IP_STATUS", length=100)
    private String     restictIpStatus ;

    @Column(name="ALLOWED_IP_ADDR", length=4000)
    private String     allowedIpAddr ;

    @Column(name="EMPLOYE_CODE", length=50)
    private String     employeCode ;

    @Column(name="MOBILE_NUMBER", length=15)
    private String     mobileNumber ;

    @Column(name="WAJAH_YN", length=10)
    private String     wajahYn ;

    @Column(name="SUMINSURED_START")
    private BigDecimal suminsuredStart ;

    @Column(name="SUB_BRANCH", length=200)
    private String     subBranch ;

    @Column(name="SUMINSURED_END")
    private BigDecimal suminsuredEnd ;

    @Column(name="SUB_USER_TYPE", length=50)
    private String     subUserType ;

    @Column(name="ENCRYPT_PASSWORD", length=1000)
    private String     encryptPassword ;

    @Column(name="TOKEN_PASSWORD", length=2000)
    private String     tokenPassword ;

    @Column(name="LOSSTYPEIDLIST", length=300)
    private String     losstypeidlist ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="COMPANY_ID", referencedColumnName="INS_ID", insertable=false, updatable=false)
    private InsuranceCompanyMaster insuranceCompanyMaster ; 

    @OneToMany(mappedBy="loginMaster")
    private List<LoginUserDetails> listOfLoginUserDetails ; 



}



