/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:43 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MailMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MailMasterId.class)
@Table(name="MAIL_MASTER")


public class MailMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="APPLICATION_ID", nullable=false, length=10)
    private String     applicationId ;

    @Id
    @Column(name="INS_COMPANY_ID", nullable=false)
    private BigDecimal insCompanyId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="MAIL_CC", length=100)
    private String     mailCc ;

    @Column(name="SMTP_HOST", length=50)
    private String     smtpHost ;

    @Column(name="SMTP_USER", length=25)
    private String     smtpUser ;

    @Column(name="SMTP_PWD", length=10)
    private String     smtpPwd ;

    @Column(name="EXP_DATE", length=10)
    private String     expDate ;

    @Column(name="EXP_TIME", length=10)
    private String     expTime ;

    @Column(name="PWD_CNT")
    private BigDecimal pwdCnt ;

    @Column(name="PWD_LEN")
    private String pwdLen ;

    @Column(name="HOME_APPLICATION_ID", length=10)
    private String     homeApplicationId ;

    @Column(name="ADDRESS", length=100)
    private String     address ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="REMARKS", length=200)
    private String     remarks ;

    @Column(name="COMPANY_NAME", length=100)
    private String     companyName ;

    @Column(name="TO_ADDRESS", length=100)
    private String     toAddress ;

    @Column(name="AUTHORIZ_YN", length=1)
    private String     authorizYn ;

    @Column(name="SMTP_PORT")
    private BigDecimal smtpPort ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE", nullable=false)
    private Date       effectiveDate ;

    @Column(name="AMENDID", nullable=false)
    private BigDecimal amendid ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRYDATE")
    private Date       entrydate ;

    @Column(name="APP_ID")
    private String appId ;
    
    @Column(name="HOME_APP")
    private String homeApp ;

    //--- ENTITY LINKS ( RELATIONSHIP )


}



