/*
 * Created on 2021-11-01 ( 15:04:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.common.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;

/**
 * Composite primary key for entity "MenuMaster" ( stored in table "MENU_MASTER" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
public class MenuMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private BigDecimal menuId ;
    
    private String     branchCode ;
    
     
}
