/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:44 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "MenuMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="MENU_MASTER")


public class MenuMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="MENU_ID", nullable=false)
    private BigDecimal menuId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="MENU_NAME", length=300)
    private String     menuName ;

    @Column(name="MENU_URL", length=4000)
    private String     menuUrl ;

    @Column(name="PARENT_MENU", length=10)
    private String     parentMenu ;

    @Column(name="BRANCH_CODE", length=10)
    private String     branchCode ;

    @Column(name="PRODUCT_ID")
    private BigDecimal productId ;

    @Column(name="STATUS", nullable=false, length=1)
    private String     status ;

    @Column(name="RSACODE", length=25)
    private String     rsacode ;

    @Column(name="USERTYPE", length=100)
    private String     usertype ;

    @Column(name="ISCLICK", length=100)
    private String     isclick ;

    @Column(name="DISPLAY_ORDER")
    private BigDecimal displayOrder ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



