/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:42 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MFieldMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="M_FIELD_MASTER")


public class MFieldMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="MF_FIELDID", nullable=false)
    private BigDecimal mfFieldid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="MF_FIELDNAME", length=100)
    private String     mfFieldname ;

    @Column(name="MF_FIELDLABELNAME", length=150)
    private String     mfFieldlabelname ;

    @Column(name="MF_INPUTFIELD", length=20)
    private String     mfInputfield ;

    @Column(name="MF_OPTIONS", length=1000)
    private String     mfOptions ;

    @Column(name="MF_DATATYPE", length=20)
    private String     mfDatatype ;

    @Column(name="MF_LENGTH")
    private BigDecimal mfLength ;

    @Column(name="MF_MANDATORY", length=5)
    private String     mfMandatory ;

    @Column(name="MF_DATETYPEFORMAT", length=20)
    private String     mfDatetypeformat ;

    @Column(name="MF_VALIDATIONMESSAGE", length=2000)
    private String     mfValidationmessage ;

    @Column(name="MF_PARENTID")
    private BigDecimal mfParentid ;

    @Column(name="MF_APIURL", length=100)
    private String     mfApiurl ;

    @Column(name="MF_VALUE", length=100)
    private String     mfValue ;

    @Column(name="MF_PARENTNAME", length=100)
    private String     mfParentname ;

    @Column(name="MF_CHILDNAME", length=100)
    private String     mfChildname ;

    @Column(name="MF_CASCADINGOPTIONS", length=1000)
    private String     mfCascadingoptions ;

    @Column(name="MF_STATUS", length=20)
    private String     mfStatus ;

    @Temporal(TemporalType.DATE)
    @Column(name="MF_ENTRYDATE")
    private Date       mfEntrydate ;

    @Column(name="MF_SEQUENCEYN", length=1)
    private String     mfSequenceyn ;

    @Column(name="MF_DISPLAY_ORDER", length=100)
    private String     mfDisplayOrder ;

    @Column(name="MF_REQUESTTYPE", length=1000)
    private String     mfRequesttype ;

    @Column(name="MF_REQUESTKEYS", length=1000)
    private String     mfRequestkeys ;

    @Column(name="MF_REQUESTVALUES", length=1000)
    private String     mfRequestvalues ;

    @Column(name="TOOLTIP_MES", length=1000)
    private String     tooltipMes ;

    @Column(name="COVERAGETYPE", length=10)
    private String     coveragetype ;

    @Column(name="UPLOADOPTION", length=10)
    private String     uploadoption ;

    @Column(name="MAXSUMINSURED")
    private BigDecimal maxsuminsured ;

    @Column(name="COVERAGELIMIT")
    private BigDecimal coveragelimit ;

    @Column(name="CALCTYPE", length=10)
    private String     calctype ;

    @Column(name="CALCSTATUS", length=10)
    private String     calcstatus ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVEDATE")
    private Date       effectivedate ;

    @Column(name="CORECODE", length=10)
    private String     corecode ;

    @Column(name="MF_OPTIONKEYS", length=10)
    private String     mfOptionkeys ;

    @Column(name="MF_OPTIONVALUES", length=10)
    private String     mfOptionvalues ;

    @Column(name="BASE_RATE", length=100)
    private String     baseRate ;

    @Column(name="CALC_YN", length=100)
    private String     calcYn ;

    @Column(name="EXCESS", length=100)
    private String     excess ;

    @Column(name="MIN_PREMIUM", length=50)
    private String     minPremium ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



