/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:42 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MModule"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="M_MODULE")


public class MModule implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="MM_MODULEID", nullable=false)
    private BigDecimal mmModuleid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="MM_MODULENAME", length=100)
    private String     mmModulename ;

    @Column(name="MC_COREAPPCODE", length=25)
    private String     mcCoreappcode ;

    @Column(name="MM_COMPANYID")
    private BigDecimal mmCompanyid ;

    @Column(name="MM_LOGINURL", length=100)
    private String     mmLoginurl ;

    @Temporal(TemporalType.DATE)
    @Column(name="MM_EFFECTIVEDATE")
    private Date       mmEffectivedate ;

    @Temporal(TemporalType.DATE)
    @Column(name="MM_ENTRYDATE")
    private Date       mmEntrydate ;

    @Column(name="MM_STATUS", length=1)
    private String     mmStatus ;

    @Column(name="MM_DISPLAYORDER")
    private BigDecimal mmDisplayorder ;

    @Column(name="MM_REMARKS", length=100)
    private String     mmRemarks ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



