/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MotorPolicyCoverData"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MotorPolicyCoverDataId.class)
@Table(name="MOTOR_POLICY_COVER_DATA")


public class MotorPolicyCoverData implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="APPLICATION_NO", nullable=false)
    private BigDecimal applicationNo ;

    @Id
    @Column(name="QUOTE_NO", nullable=false)
    private BigDecimal quoteNo ;

    @Id
    @Column(name="POLICYTYPE_COVERID", nullable=false)
    private BigDecimal policytypeCoverid ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    @Id
    @Column(name="VEHICLE_ID", nullable=false)
    private BigDecimal vehicleId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SUM_INSURED")
    private BigDecimal sumInsured ;

    @Column(name="RATE")
    private BigDecimal rate ;

    @Column(name="PREMIUM")
    private BigDecimal premium ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPIRY_DATE")
    private Date       expiryDate ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    @Column(name="OPCOVER_DESC", length=1000)
    private String     opcoverDesc ;

    @Column(name="DESCRIPTION", length=1000)
    private String     description ;

    @Column(name="GROUP_DESC", length=1000)
    private String     groupDesc ;

    @Column(name="GROUP_ID")
    private BigDecimal groupId ;

    @Column(name="DISPLAY_ORDER")
    private BigDecimal displayOrder ;

    @Column(name="USD_PREMIUM")
    private BigDecimal usdPremium ;

    @Column(name="USD_SUM_INSURED")
    private BigDecimal usdSumInsured ;

    @Column(name="CURRENCY_ID", length=10)
    private String     currencyId ;

    @Column(name="USD_RATE")
    private BigDecimal usdRate ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



