/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:46 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.*;




/**
* Domain class for entity "MotorGroupMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="MOTOR_GROUP_MASTER")


public class MotorGroupMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="GROUP_ID", nullable=false)
    private BigDecimal groupId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="GROUP_DESC_ENGLISH", length=100)
    private String     groupDescEnglish ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPIRY_DATE")
    private Date       expiryDate ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    @Column(name="DISPLAY_ORDER")
    private BigDecimal displayOrder ;

    @Column(name="INT_TYPE", length=10)
    private String     intType ;

    @Column(name="CORE_APP_CODE", length=10)
    private String     coreAppCode ;

    @Column(name="CALC_TYPE", length=10)
    private String     calcType ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="motorGroupMaster")
    private List<MotorOpcoverDetails> listOfMotorOpcoverDetails ; 



}



