/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:45 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:45 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.*;




/**
* Domain class for entity "MotorFactorMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="MOTOR_FACTOR_MASTER")


public class MotorFactorMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="FACTOR_ID", nullable=false)
    private BigDecimal factorId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="FACTOR_NAME", length=250)
    private String     factorName ;

    @Column(name="FACTOR_TYPE_DESC", length=800)
    private String     factorTypeDesc ;

    @Column(name="RATING_TYPE", length=180)
    private String     ratingType ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Column(name="END_DATE", length=250)
    private String     endDate ;

    @Column(name="STATUS", length=15)
    private String     status ;

    @Column(name="FACTOR_TYPE", length=150)
    private String     factorType ;

    @Column(name="RATING_COLUMN", length=250)
    private String     ratingColumn ;

    @Column(name="REMARKS", length=800)
    private String     remarks ;

    @Column(name="DATA_FORMULA", length=20)
    private String     dataFormula ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="motorFactorMaster")
    private List<MotorFactorRateMaster> listOfMotorFactorRateMaster ; 



}



