/*
 * Created on 2022-02-11 ( 19:14:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.common.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;

/**
 * Composite primary key for entity "MotorPolicyCoverData" ( stored in table "MOTOR_POLICY_COVER_DATA" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MotorPolicyCoverDataId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private BigDecimal applicationNo ;
    
    private BigDecimal quoteNo ;
    
    private BigDecimal policytypeCoverid ;
    
    private String     branchCode ;
    
    private BigDecimal vehicleId ;
    
     
}
