/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:44 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MotorDataDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MotorDataDetailId.class)
@Table(name="MOTOR_DATA_DETAIL")


public class MotorDataDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="APPLICATION_NO", nullable=false)
    private BigDecimal applicationNo ;

    @Id
    @Column(name="QUOTE_NO", nullable=false)
    private BigDecimal quoteNo ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Column(name="VEHICLE_ID", nullable=false)
    private BigDecimal vehicleId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CUSTOMER_ID")
    private BigDecimal customerId ;

    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="SCHEME_ID")
    private BigDecimal schemeId ;

    @Column(name="MAKE_ID")
    private BigDecimal makeId ;

    @Column(name="MODEL_ID")
    private BigDecimal modelId ;

    @Column(name="BODY")
    private BigDecimal body ;

    @Column(name="MANUFACTURE_YEAR", length=4)
    private String     manufactureYear ;

    @Column(name="MANUFACTURE_MONTH", length=2)
    private String     manufactureMonth ;

    @Column(name="CUBIC_CAPACITY")
    private BigDecimal cubicCapacity ;

    @Column(name="SEATING_CAPACITY")
    private BigDecimal seatingCapacity ;

    @Column(name="SUMINSURED_VALUE_FOREIGN")
    private BigDecimal suminsuredValueForeign ;

    @Column(name="SUMINSURED_VALUE_LOCAL")
    private BigDecimal suminsuredValueLocal ;

    @Column(name="CURRENCY_TYPE", length=50)
    private String     currencyType ;

    @Column(name="VEHICLE_TYPE")
    private BigDecimal vehicleType ;

    @Column(name="LEASED", length=1)
    private String     leased ;

    @Column(name="NO_OF_CYLINDER")
    private BigDecimal noOfCylinder ;

    @Column(name="AGENCY_REPAIR", length=1)
    private String     agencyRepair ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DRIVER_DOB")
    private Date       driverDob ;

    @Column(name="DRIVER_AGE")
    private BigDecimal driverAge ;

    @Column(name="DRIVER_UAE_LICENCE")
    private BigDecimal driverUaeLicence ;

    @Column(name="DRIVER_OTHER_LICENCE")
    private BigDecimal driverOtherLicence ;

    @Column(name="NO_OF_CLAIMS")
    private BigDecimal noOfClaims ;

    @Column(name="NO_CLAIM_BONUS")
    private BigDecimal noClaimBonus ;

    @Column(name="AREA_COVERAGE")
    private BigDecimal areaCoverage ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INCEPTION_DATE")
    private Date       inceptionDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPIRY_DATE")
    private Date       expiryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDORSEMENT_DATE")
    private Date       endorsementDate ;

    @Column(name="DRIVER_GENDER", length=1)
    private String     driverGender ;

    @Column(name="THIRD_PARTY_LIABILITY")
    private BigDecimal thirdPartyLiability ;

    @Column(name="DRIVER_NATIONALITY")
    private BigDecimal driverNationality ;

    @Column(name="DRIVER_LICENSE", length=25)
    private String     driverLicense ;

    @Column(name="PERSONAL_ACCIDENT_DRIVER", length=1)
    private String     personalAccidentDriver ;

    @Column(name="PERSONAL_ACCIDENT_PASSENGER", length=1)
    private String     personalAccidentPassenger ;

    @Column(name="REGISTRATION_NO", length=25)
    private String     registrationNo ;

    @Column(name="CHASSIS_NO", length=25)
    private String     chassisNo ;

    @Column(name="ENGINE_NUMBER", length=25)
    private String     engineNumber ;

    @Column(name="PLATE_COLOR")
    private BigDecimal plateColor ;

    @Column(name="VEHICLE_COLOR")
    private BigDecimal vehicleColor ;

    @Column(name="INSURED_NAME_ARABIC", length=2000)
    private String     insuredNameArabic ;

    @Column(name="INSURED_ADDRESS_ARABIC", length=4000)
    private String     insuredAddressArabic ;

    @Column(name="BANK_NAME")
    private BigDecimal bankName ;

    @Column(name="BASE_RATE")
    private BigDecimal baseRate ;

    @Column(name="PREMIUM")
    private BigDecimal premium ;

    @Column(name="DISCOUNT_PREMIUM")
    private BigDecimal discountPremium ;

    @Column(name="AGENCY_REPAIR_PREMIUM")
    private BigDecimal agencyRepairPremium ;

    @Column(name="PA_DRIVER_PREMIUM")
    private BigDecimal paDriverPremium ;

    @Column(name="PA_PASSENGER_PREMIUM")
    private BigDecimal paPassengerPremium ;

    @Column(name="POLICYTYPE", nullable=false)
    private BigDecimal policytype ;

    @Column(name="OPTIONAL_COVER", length=50)
    private String     optionalCover ;

    @Column(name="EXCESS")
    private BigDecimal excess ;

    @Column(name="BANK_ID")
    private BigDecimal bankId ;

    @Column(name="REGISTER_LOCATION", length=100)
    private String     registerLocation ;

    @Column(name="TRAFFIC_ID")
    private BigDecimal trafficId ;

    @Column(name="ENDORSEMENT_STATUS", length=1)
    private String     endorsementStatus ;

    @Column(name="PDF_BROKER_STATUS")
    private BigDecimal pdfBrokerStatus ;

    @Column(name="CLAIMYN", length=1)
    private String     claimyn ;

    @Column(name="CLAIM_AMOUNT")
    private BigDecimal claimAmount ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DRIVER_UAE_LIC_EXP_DT")
    private Date       driverUaeLicExpDt ;

    @Column(name="REGISTRATION_YEAR", length=10)
    private String     registrationYear ;

    @Column(name="REFERRAL_REMARKS", length=500)
    private String     referralRemarks ;

    @Column(name="DEDUCTIBLE_ID")
    private BigDecimal deductibleId ;

    @Column(name="MANUFACTURE_LOC")
    private BigDecimal manufactureLoc ;

    @Column(name="DRIVER_ID", length=50)
    private String     driverId ;

    @Column(name="ELECTRICAL_SI")
    private BigDecimal electricalSi ;

    @Column(name="NONELECTRICAL_SI")
    private BigDecimal nonelectricalSi ;

    @Column(name="PREV_POLICYNO", length=100)
    private String     prevPolicyno ;

    @Column(name="INS_COMPANY", length=200)
    private String     insCompany ;

    @Temporal(TemporalType.DATE)
    @Column(name="PREV_POLICYEXPIRYDATE")
    private Date       prevPolicyexpirydate ;

    @Column(name="VAT")
    private BigDecimal vat ;

    @Column(name="NONELECTRICAL_RATE")
    private BigDecimal nonelectricalRate ;

    @Column(name="NONELECTRICAL_PREM")
    private BigDecimal nonelectricalPrem ;

    @Column(name="ELECTRICAL_RATE")
    private BigDecimal electricalRate ;

    @Column(name="ELECTRICAL_PREM")
    private BigDecimal electricalPrem ;

    @Column(name="CURRENCY_ID")
    private BigDecimal currencyId ;

    @Column(name="POLICY_NO", length=100)
    private String     policyNo ;

    @Column(name="OWNNERDRIVER_YN", length=1)
    private String     ownnerdriverYn ;

    @Column(name="EXCHANGE_RATE")
    private BigDecimal exchangeRate ;

    @Column(name="ORIGINAL_POLICY_NO", length=100)
    private String     originalPolicyNo ;

    @Column(name="SUMINSURED_VALUE_LOCAL_ENDT")
    private BigDecimal suminsuredValueLocalEndt ;

    @Column(name="ELECTRICAL_SI_ENDT")
    private BigDecimal electricalSiEndt ;

    @Column(name="NONELECTRICAL_SI_ENDT")
    private BigDecimal nonelectricalSiEndt ;

    @Column(name="CERTIFICATE_NO", length=20)
    private String     certificateNo ;

    @Column(name="ONLINE_DISCOUNT")
    private BigDecimal onlineDiscount ;

    @Column(name="DEDUCTIBLE_AMOUNT")
    private BigDecimal deductibleAmount ;

    @Column(name="CUSTOMER_TYPE", length=100)
    private String     customerType ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



