/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:45 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:45 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MotorFactorRateMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MotorFactorRateMasterId.class)
@Table(name="MOTOR_FACTOR_RATE_MASTER")


public class MotorFactorRateMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="FACTOR_RATE_ID", nullable=false)
    private BigDecimal factorRateId ;

    @Id
    @Column(name="POLICYTYPE_ID", nullable=false)
    private BigDecimal policytypeId ;

    @Id
    @Column(name="AGENCY_CODE", nullable=false, length=80)
    private String     agencyCode ;

    @Id
    @Column(name="FACTOR_ID", nullable=false)
    private BigDecimal factorId ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    @Id
    @Column(name="DIVISION_CODE", nullable=false, length=80)
    private String     divisionCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="RATE")
    private BigDecimal rate ;

    @Column(name="STATUS", length=15)
    private String     status ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE")
    private Date       endDate ;

    @Column(name="PARAM1")
    private BigDecimal param1 ;

    @Column(name="PARAM2")
    private BigDecimal param2 ;

    @Column(name="PARAM3", length=80)
    private String     param3 ;

    @Column(name="PARAM4", length=80)
    private String     param4 ;

    @Column(name="PARAM5")
    private BigDecimal param5 ;

    @Column(name="PARAM6")
    private BigDecimal param6 ;

    @Column(name="PARAM7")
    private BigDecimal param7 ;

    @Column(name="PARAM8")
    private BigDecimal param8 ;

    @Column(name="PARAM9")
    private BigDecimal param9 ;

    @Column(name="PARAM10")
    private BigDecimal param10 ;

    @Column(name="CONFIG_TYPE", length=80)
    private String     configType ;

    @Column(name="REMARKS", length=880)
    private String     remarks ;

    @Column(name="RATING_TYPE", length=150)
    private String     ratingType ;

    @Column(name="CUSTOMERCODE", length=80)
    private String     customercode ;

    @Column(name="ELECTRICAL")
    private BigDecimal electrical ;

    @Column(name="NONELECTRICAL")
    private BigDecimal nonelectrical ;

    @Column(name="VEHUSAGEID")
    private BigDecimal vehusageid ;

    @Column(name="BODYID")
    private BigDecimal bodyid ;

    @Column(name="CUSTOMER_TYPE", length=80)
    private String     customerType ;

    @Column(name="UPLOAD_TRANID")
    private BigDecimal uploadTranid ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="POLICYTYPE_ID", referencedColumnName="POLICYTYPE_ID", insertable=false, updatable=false)
    private MotorPolicytypeMaster motorPolicytypeMaster ; 

    @ManyToOne
    @JoinColumn(name="FACTOR_ID", referencedColumnName="FACTOR_ID", insertable=false, updatable=false)
    private MotorFactorMaster motorFactorMaster ; 



}



