/*
 * Created on 2022-02-11 ( 19:14:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.common.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;

/**
 * Composite primary key for entity "MotorOpcoverDetails" ( stored in table "MOTOR_OPCOVER_DETAILS" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MotorOpcoverDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private BigDecimal policySubtypeId ;
    
    private BigDecimal opcoverId ;
    
    private BigDecimal opcoversubId ;
    
    private BigDecimal amendId ;
    
    private BigDecimal groupId ;
    
     
}
