/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.*;




/**
* Domain class for entity "MotorPolicytypeMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="MOTOR_POLICYTYPE_MASTER")


public class MotorPolicytypeMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="POLICYTYPE_ID", nullable=false)
    private BigDecimal policytypeId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="COREAPP_CODE", nullable=false, length=10)
    private String     coreappCode ;

    @Column(name="POLICYTYPE_DESC_ENGLISH", length=100)
    private String     policytypeDescEnglish ;

    @Column(name="POLICYTYPE_DESC_ARABIC", length=1600)
    private String     policytypeDescArabic ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPIRY_DATE")
    private Date       expiryDate ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    @Column(name="POLICY_TERM")
    private BigDecimal policyTerm ;

    @Column(name="POLICYTYPE_NAME", length=100)
    private String     policytypeName ;

    @Column(name="POLICY_SUBTYPE_ID")
    private BigDecimal policySubtypeId ;

    @Column(name="PAYMENT_YN", length=1)
    private String     paymentYn ;

    @Column(name="TYPE", length=20)
    private String     type ;

    @Column(name="COREAPPCODE", length=20)
    private String     coreappcode ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="motorPolicytypeMaster")
    private List<MotorOpcoverDetails> listOfMotorOpcoverDetails ; 

    @OneToMany(mappedBy="motorPolicytypeMaster")
    private List<MotorFactorRateMaster> listOfMotorFactorRateMaster ; 



}



