/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:44 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MotorDeductibleMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MotorDeductibleMasterId.class)
@Table(name="MOTOR_DEDUCTIBLE_MASTER")


public class MotorDeductibleMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="DEDUCT_ID", nullable=false)
    private BigDecimal deductId ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="DEDUCT_START")
    private BigDecimal deductStart ;

    @Column(name="DEDUCT_END")
    private BigDecimal deductEnd ;

    @Column(name="RATE")
    private BigDecimal rate ;

    @Column(name="DISC_AMT")
    private BigDecimal discAmt ;

    @Column(name="STATUS", length=10)
    private String     status ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Column(name="REMARKS", length=500)
    private String     remarks ;

    @Column(name="BRANCH_CODE", length=10)
    private String     branchCode ;

    @Column(name="TYPE_OF_BODY_ID")
    private BigDecimal typeOfBodyId ;

    @Column(name="DEFAULT_YN", length=1)
    private String     defaultYn ;

    @Column(name="SEATING_START")
    private BigDecimal seatingStart ;

    @Column(name="SEATING_END")
    private BigDecimal seatingEnd ;

    @Column(name="DEDUCT_AMT_USD")
    private BigDecimal deductAmtUsd ;

    @Column(name="THEFT_EXCESS")
    private BigDecimal theftExcess ;

    @Column(name="THEFT_EXCESS_USD")
    private BigDecimal theftExcessUsd ;

    @Column(name="DRIVER_EXCESS")
    private BigDecimal driverExcess ;

    @Column(name="DRIVER_EXCESS_USD")
    private BigDecimal driverExcessUsd ;

    @Column(name="CLAIM_EXCESS")
    private BigDecimal claimExcess ;

    @Column(name="CLAIM_EXCESS_USD")
    private BigDecimal claimExcessUsd ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



