/*
 * Created on 2022-02-11 ( 19:14:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.common.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;

/**
 * Composite primary key for entity "MsCommonDetail" ( stored in table "MS_COMMON_DETAIL" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MsCommonDetailId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     requestreferenceno ;
    
    private BigDecimal cdreferenceno ;
    
    private BigDecimal vdreferenceno ;
    
    private BigDecimal policytypeid ;
    
    private BigDecimal ebrokerid ;
    
    private String     agencycode ;
    
    private String     schemecode ;
    
    private BigDecimal vehicletype ;
    
    private BigDecimal suminsured ;
    
    private String     havepromocode ;
    
    private String     promocode ;
    
    private BigDecimal noofdays ;
    
    private String     usertype ;
    
    private String     promoempcode ;
    
    private String     bdmcode ;
    
    private String     interestedinCompyn ;
    
    private String     prevcompanyid ;
    
    private String     prevtplpolicyyn ;
    
     
}
