/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:50 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.*;




/**
* Domain class for entity "MsCustomerDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="MS_CUSTOMER_DETAIL")


public class MsCustomerDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="CD_CUSTOMER_ID", nullable=false)
    private BigDecimal cdCustomerId ;

    //--- ENTITY DATA FIELDS 
    @Temporal(TemporalType.DATE)
    @Column(name="CD_DOBG")
    private Date       cdDobg ;

    @Column(name="CD_AGE")
    private BigDecimal cdAge ;

    @Column(name="CD_GENDER")
    private BigDecimal cdGender ;

    @Column(name="CD_GENDER_EN", length=20)
    private String     cdGenderEn ;

    @Column(name="CD_GENDER_AR", length=60)
    private String     cdGenderAr ;

    @Column(name="CD_PROFESSION")
    private BigDecimal cdProfession ;

    @Column(name="CD_PROFESSION_EN", length=200)
    private String     cdProfessionEn ;

    @Column(name="CD_PROFESSION_AR", length=400)
    private String     cdProfessionAr ;

    @Column(name="CD_REGION")
    private BigDecimal cdRegion ;

    @Column(name="CD_REGION_EN", length=80)
    private String     cdRegionEn ;

    @Column(name="CD_REGION_AR", length=160)
    private String     cdRegionAr ;

    @Column(name="CD_LICENCETYPE_ID")
    private BigDecimal cdLicencetypeId ;

    @Column(name="CD_LICENCETYPE_DESC", length=250)
    private String     cdLicencetypeDesc ;

    @Column(name="CD_LICENCE_VALIDPERIOD")
    private BigDecimal cdLicenceValidperiod ;

    @Temporal(TemporalType.DATE)
    @Column(name="CD_LICENCE_VALIDITYDATE")
    private Date       cdLicenceValiditydate ;

    @Column(name="CD_LICENCE_EXPERIENCE")
    private BigDecimal cdLicenceExperience ;

    @Column(name="CD_VOLUMEOFCARS")
    private BigDecimal cdVolumeofcars ;

    @Column(name="CD_NOOFACCIDENTS")
    private BigDecimal cdNoofaccidents ;

    @Column(name="CD_DRIVER_OFFENCE")
    private BigDecimal cdDriverOffence ;

    @Column(name="CD_LOYALTY")
    private BigDecimal cdLoyalty ;

  /*  @Column(name="CD_REFERENCENO")
    private BigDecimal cdReferenceno ; */

    @Column(name="CD_STATUS", length=8)
    private String     cdStatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CD_ENTRYDATE")
    private Date       cdEntrydate ;

    @Column(name="CD_REMARKS", length=100)
    private String     cdRemarks ;

    @Column(name="CD_NATIONALITY_ID")
    private BigDecimal cdNationalityId ;

    @Column(name="CD_NATIONALITY_EN", length=100)
    private String     cdNationalityEn ;

    @Column(name="CD_NATIONALITY_AR", length=200)
    private String     cdNationalityAr ;

    @Column(name="CD_CIVILID", length=100)
    private String     cdCivilid ;

    @Column(name="CD_VISSTATUSID")
    private BigDecimal cdVisstatusid ;

    @Column(name="CD_LICENCEEXPIREDYN", length=5)
    private String     cdLicenceexpiredyn ;

    @Column(name="CD_DRIVINGTYPEID")
    private BigDecimal cdDrivingtypeid ;

    @Column(name="CD_DRIVINGTYPEDESC", length=50)
    private String     cdDrivingtypedesc ;

    @Column(name="CD_TITLE", length=10)
    private String     cdTitle ;

    @Column(name="CD_FIRST_NAME", length=50)
    private String     cdFirstName ;

    @Column(name="CD_LAST_NAME", length=30)
    private String     cdLastName ;

    @Column(name="CD_MOBILE_NO", length=20)
    private String     cdMobileNo ;

    @Column(name="CD_EMAIL", length=50)
    private String     cdEmail ;

    @Column(name="CD_NRCARD_NO", length=50)
    private String     cdNrcardNo ;

    @Column(name="CD_CUSTOMER_TYPE", length=10)
    private String     cdCustomerType ;

    @Column(name="CD_POBOX", length=10)
    private String     cdPobox ;

    @Column(name="CD_ALTERNATE_MOBILE", length=20)
    private String     cdAlternateMobile ;

    @Column(name="CD_CITY", length=70)
    private String     cdCity ;

    @Column(name="CD_PASSPORT_NUMBER", length=60)
    private String     cdPassportNumber ;

    @Column(name="CD_COMPANY_REG_NO", length=50)
    private String     cdCompanyRegNo ;

    @Column(name="CD_LOGIN_ID", length=20)
    private String     cdLoginId ;

/*    @Column(name="CD_QUOTE_NO", length=20)
    private String     cdQuoteNo ; */

    @Column(name="CD_BROKER_CODE", length=20)
    private String     cdBrokerCode ;

    @Column(name="CD_AGENCY_CODE", length=20)
    private String     cdAgencyCode ;

    @Temporal(TemporalType.DATE)
    @Column(name="CD_EFFECTIVE_DATE")
    private Date       cdEffectiveDate ;

    @Column(name="CD_APPLICAION_ID", length=30)
    private String     cdApplicaionId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="msCustomerDetail")
    private List<EserviceRequestDetail> listOfEserviceRequestDetail ; 



}



