/*
 * Created on 2022-02-11 ( 19:14:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.common.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;

/**
 * Composite primary key for entity "MSubscreen" ( stored in table "M_SUBSCREEN" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MSubscreenId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private BigDecimal mssModuleid ;
    
    private BigDecimal mssScreenid ;
    
    private BigDecimal mssSubscreenid ;
    
     
}
