/*
 * Created on 2022-02-11 ( 19:14:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.common.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;
import java.util.Date;

/**
 * Composite primary key for entity "MsVehicleDetail" ( stored in table "MS_VEHICLE_DETAIL" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MsVehicleDetailId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private BigDecimal vdBodytype ;
    
    private BigDecimal vdSeatingcapacity ;
    
    private BigDecimal vdVehusageid ;
    
    private BigDecimal vdReferenceno ;
    
    private Date       vdPolicystartdate ;
    
    private BigDecimal vdDrReferenceno ;
    
    private BigDecimal vdCustomerid ;
    
    private String     vdDrCivilid ;
    
    private BigDecimal vdEnginecapacity ;
    
     
}
