/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:51 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MsVehicleDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MsVehicleDetailId.class)
@Table(name="MS_VEHICLE_DETAIL")


public class MsVehicleDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="VD_BODYTYPE", nullable=false)
    private BigDecimal vdBodytype ;

    @Id
    @Column(name="VD_SEATINGCAPACITY", nullable=false)
    private BigDecimal vdSeatingcapacity ;

    @Id
    @Column(name="VD_VEHUSAGEID", nullable=false)
    private BigDecimal vdVehusageid ;

    @Id
    @Column(name="VD_REFERENCENO", nullable=false)
    private BigDecimal vdReferenceno ;

    @Id
    @Temporal(TemporalType.DATE)
    @Column(name="VD_POLICYSTARTDATE", nullable=false)
    private Date       vdPolicystartdate ;

    @Id
    @Column(name="VD_DR_REFERENCENO", nullable=false)
    private BigDecimal vdDrReferenceno ;

    @Id
    @Column(name="VD_CUSTOMERID", nullable=false)
    private BigDecimal vdCustomerid ;

    @Id
    @Column(name="VD_DR_CIVILID", nullable=false, length=100)
    private String     vdDrCivilid ;

    @Id
    @Column(name="VD_ENGINECAPACITY", nullable=false)
    private BigDecimal vdEnginecapacity ;

    //--- ENTITY DATA FIELDS 
    @Column(name="VD_CHASSISNO", length=50)
    private String     vdChassisno ;

    @Column(name="VD_PLATENO", length=100)
    private String     vdPlateno ;

    @Column(name="VD_PLATECHAR", length=100)
    private String     vdPlatechar ;

    @Column(name="VD_PLATECHAR_EN", length=100)
    private String     vdPlatecharEn ;

    @Column(name="VD_PLATECHAR_AR", length=200)
    private String     vdPlatecharAr ;

    @Column(name="VD_MAKE")
    private BigDecimal vdMake ;

    @Column(name="VD_MAKENAME_EN", length=60)
    private String     vdMakenameEn ;

    @Column(name="VD_MAKENAME_AR", length=200)
    private String     vdMakenameAr ;

    @Column(name="VD_MODEL")
    private BigDecimal vdModel ;

    @Column(name="VD_MODELNAME_EN", length=60)
    private String     vdModelnameEn ;

    @Column(name="VD_MODELNAME_AR", length=200)
    private String     vdModelnameAr ;

    @Column(name="VD_BODYTYPE_EN", length=60)
    private String     vdBodytypeEn ;

    @Column(name="VD_BODYTYPE_AR", length=200)
    private String     vdBodytypeAr ;

    @Column(name="VD_TRIM")
    private BigDecimal vdTrim ;

    @Column(name="VD_TRIMNAME_EN", length=60)
    private String     vdTrimnameEn ;

    @Column(name="VD_TRIMNAME_AR", length=200)
    private String     vdTrimnameAr ;

    @Column(name="VD_VEHCOLORID")
    private BigDecimal vdVehcolorid ;

    @Column(name="VD_VEHCOLOR", length=60)
    private String     vdVehcolor ;

    @Column(name="VD_MANFCOUNTRY_ID")
    private BigDecimal vdManfcountryId ;

    @Column(name="VD_MANFYEAR")
    private BigDecimal vdManfyear ;

    @Column(name="VD_VEHREGN_DATE", length=20)
    private String     vdVehregnDate ;

    @Column(name="VD_VEHAGE")
    private BigDecimal vdVehage ;

    @Column(name="VD_CHASSIS_CLAIM")
    private BigDecimal vdChassisClaim ;

    @Column(name="VD_VEHCONDITION", length=30)
    private String     vdVehcondition ;

    @Column(name="VD_ODOMETER")
    private BigDecimal vdOdometer ;

    @Column(name="VD_EXPECTEDMILEAGE")
    private BigDecimal vdExpectedmileage ;

    @Column(name="VD_CLAIMAMT")
    private BigDecimal vdClaimamt ;

    @Column(name="VD_CLAIMBONUS")
    private BigDecimal vdClaimbonus ;

    @Column(name="VD_GEOEXTENSION")
    private BigDecimal vdGeoextension ;

    @Column(name="VD_GEOEXTENSION_DESC", length=60)
    private String     vdGeoextensionDesc ;

    @Column(name="VD_IMPORT_YN", length=5)
    private String     vdImportYn ;

    @Column(name="VD_IMPORT_CODE", length=60)
    private String     vdImportCode ;

    @Column(name="VD_IMPORT_COUNTRY", length=60)
    private String     vdImportCountry ;

    @Column(name="VD_ISCOMMERICAL_YN", length=5)
    private String     vdIscommericalYn ;

    @Column(name="VD_GREYIMPORT_YN", length=5)
    private String     vdGreyimportYn ;

    @Column(name="VD_NAMEDDRIVER_CNT")
    private BigDecimal vdNameddriverCnt ;

    @Column(name="VD_STATUS", length=5)
    private String     vdStatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="VD_ENTRYDATE")
    private Date       vdEntrydate ;

    @Column(name="VD_REMARKS", length=100)
    private String     vdRemarks ;

    @Column(name="VD_ENGINENO", length=60)
    private String     vdEngineno ;

    @Column(name="VD_RENEWAL_YN", length=20)
    private String     vdRenewalYn ;

    @Column(name="VD_RENEWAL_POLICYNO", length=100)
    private String     vdRenewalPolicyno ;

    @Column(name="VD_RENEWAL_CLAIMAMT")
    private BigDecimal vdRenewalClaimamt ;

    @Column(name="VD_PLATE_NATIONALITY")
    private BigDecimal vdPlateNationality ;

    @Column(name="VD_CIVILID", length=100)
    private String     vdCivilid ;

    @Column(name="VD_BREAKININSURANCE_YN", length=5)
    private String     vdBreakininsuranceYn ;

    @Column(name="VD_TONNAGE")
    private BigDecimal vdTonnage ;

    @Column(name="VD_SALVAGEYN", length=5)
    private String     vdSalvageyn ;

    @Column(name="VD_PREMIA_CHASSIS_CLAIM")
    private BigDecimal vdPremiaChassisClaim ;

    @Column(name="VD_VEHICLE_ID")
    private BigDecimal vdVehicleId ;

    @Column(name="VD_EXCESS_AMT")
    private BigDecimal vdExcessAmt ;

    @Column(name="VD_LEASEDYN", length=1)
    private String     vdLeasedyn ;

    @Temporal(TemporalType.DATE)
    @Column(name="VD_DR_DOB")
    private Date       vdDrDob ;

    @Column(name="VD_DR_AGE")
    private BigDecimal vdDrAge ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



