/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:51 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "NotifTemplateMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(NotifTemplateMasterId.class)
@Table(name="NOTIF_TEMPLATE_MASTER")


public class NotifTemplateMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="SNO", nullable=false)
    private BigDecimal sno ;

    @Id
    @Column(name="STATUS", nullable=false, length=1)
    private String     status ;

    @Id
    @Column(name="INS_ID", nullable=false)
    private BigDecimal insId ;

    @Id
    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE", nullable=false)
    private Date       effectiveDate ;

    @Id
    @Column(name="AMENDID", nullable=false)
    private BigDecimal amendid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="MAIL_REQUIRED", length=10)
    private String     mailRequired ;

    @Column(name="MAIL_SUBJECT", length=200)
    private String     mailSubject ;

    @Column(name="MAIL_BODY", length=4000)
    private String     mailBody ;

    @Column(name="MAIL_REGARDS", length=1000)
    private String     mailRegards ;

    @Column(name="SMS_REQUIRED", length=10)
    private String     smsRequired ;

    @Column(name="SMS_SUBJECT", length=200)
    private String     smsSubject ;

    @Column(name="SMS_BODY_EN", length=4000)
    private String     smsBodyEn ;

    @Column(name="SMS_BODY_AR", length=4000)
    private String     smsBodyAr ;

    @Column(name="SMS_REGARDS", length=1000)
    private String     smsRegards ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="EMAIL_TO", length=4000)
    private String     emailTo ;

    @Column(name="EMAIL_CC", length=4000)
    private String     emailCc ;

    @Column(name="USER_TYPE", length=4000)
    private String     userType ;

    @Column(name="SMS_TO", length=4000)
    private String     smsTo ;

    @Column(name="SMS_REGARDS_AR", length=50)
    private String     smsRegardsAr ;

    @Column(name="PRODUCT_ID")
    private BigDecimal productId ;

    @Column(name="WHATSAPP_REQUIRED", length=10)
    private String     whatsappRequired ;

    @Column(name="MAIL_BODY_AR", length=4000)
    private String     mailBodyAr ;

    @Column(name="MAIL_REGARDS_AR", length=4000)
    private String     mailRegardsAr ;

    @Column(name="FILE_YN", length=10)
    private String     fileYn ;

    @Column(name="SHORT_REMARKS", length=100)
    private String     shortRemarks ;

    @Column(name="HIT_TYPE", length=10)
    private String     hitType ;

    @Column(name="WHATSAPP_SUBJECT", length=200)
    private String     whatsappSubject ;

    @Column(name="WHATSAPP_BODY_EN", length=4000)
    private String     whatsappBodyEn ;

    @Column(name="WHATSAPP_BODY_AR", length=4000)
    private String     whatsappBodyAr ;

    @Column(name="WHATSAPP_REGARDS", length=1000)
    private String     whatsappRegards ;

    @Column(name="WHATSAPP_REGARDS_AR", length=2000)
    private String     whatsappRegardsAr ;

    @Column(name="QUERY_KEY", length=100)
    private String     queryKey ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



