/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:51 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "OfsAddonExtensionMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(OfsAddonExtensionMasterId.class)
@Table(name="OFS_ADDON_EXTENSION_MASTER")


public class OfsAddonExtensionMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="SNO", nullable=false)
    private BigDecimal sno ;

    @Id
    @Column(name="OPCOVEREXT_ID", nullable=false)
    private BigDecimal opcoverextId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Column(name="SCHEME_ID", nullable=false)
    private BigDecimal schemeId ;

    @Id
    @Column(name="STATUS", nullable=false, length=1)
    private String     status ;

    //--- ENTITY DATA FIELDS 
    @Column(name="OPCOVEREXT_DESC", length=1000)
    private String     opcoverextDesc ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRYDATE")
    private Date       entrydate ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVEDATE")
    private Date       effectivedate ;

    @Column(name="REMARKS", length=1000)
    private String     remarks ;

    @Column(name="CORE_APP_CODE", length=10)
    private String     coreAppCode ;

    @Column(name="SCHEME_NAME", length=500)
    private String     schemeName ;

    @Column(name="RATE")
    private BigDecimal rate ;

    @Column(name="PERCENTAGE")
    private BigDecimal percentage ;

    @Column(name="AGENCY_CODE", length=25)
    private String     agencyCode ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



