/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:52 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:52 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "OfsClausesMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(OfsClausesMasterId.class)
@Table(name="OFS_CLAUSES_MASTER")


public class OfsClausesMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Column(name="SCHEME_ID", nullable=false)
    private BigDecimal schemeId ;

    @Id
    @Column(name="COVER_ID", nullable=false)
    private BigDecimal coverId ;

    @Id
    @Column(name="CLAUSES_ID", nullable=false)
    private BigDecimal clausesId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SNO", nullable=false)
    private BigDecimal sno ;

    @Column(name="COVER_TYPE", length=100)
    private String     coverType ;

    @Column(name="CLAUSES_DESCRIPTION", nullable=false, length=1000)
    private String     clausesDescription ;

    @Column(name="DISPLAY_ORDER")
    private BigDecimal displayOrder ;

    @Column(name="EXTRA_COVER_ID")
    private BigDecimal extraCoverId ;

    @Column(name="CORE_APP_CODE", length=10)
    private String     coreAppCode ;

    @Column(name="STATUS", nullable=false, length=1)
    private String     status ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



