/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:52 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:52 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "OfsConfigMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(OfsConfigMasterId.class)
@Table(name="OFS_CONFIG_MASTER")


public class OfsConfigMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="OFS_CONFIG_ID", nullable=false)
    private BigDecimal ofsConfigId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Column(name="SCHEME_ID", nullable=false)
    private BigDecimal schemeId ;

    @Id
    @Column(name="COVERAGES_ID", nullable=false)
    private BigDecimal coveragesId ;

    @Id
    @Column(name="COVERAGES_SUB_ID", nullable=false)
    private BigDecimal coveragesSubId ;

    @Id
    @Column(name="MODULE_ID", nullable=false)
    private BigDecimal moduleId ;

    @Id
    @Column(name="SCREEN_ID", nullable=false)
    private BigDecimal screenId ;

    @Id
    @Column(name="SUBSCREEN_ID", nullable=false)
    private BigDecimal subscreenId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CONTENT_TYPE_ID", nullable=false)
    private BigDecimal contentTypeId ;

    @Column(name="DISPLAY_NAME", nullable=false, length=500)
    private String     displayName ;

    @Column(name="DISPLAY_TYPE", length=15)
    private String     displayType ;

    @Column(name="DISPLAY_ORDER")
    private BigDecimal displayOrder ;

    @Column(name="DROPDOWN_KEY", length=25)
    private String     dropdownKey ;

    @Column(name="DROPDOWN_VALUE", length=25)
    private String     dropdownValue ;

    @Column(name="DROPDOWN_TABLE", length=25)
    private String     dropdownTable ;

    @Column(name="VALIDATION_TYPE", length=25)
    private String     validationType ;

    @Column(name="DEST_TABLE", length=25)
    private String     destTable ;

    @Column(name="DEST_COLUMN", length=25)
    private String     destColumn ;

    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="MANDATORY", length=100)
    private String     mandatory ;

    @Column(name="TOTAL_SUMINSURED_YN", length=1)
    private String     totalSuminsuredYn ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Column(name="FIELD_NAME", length=100)
    private String     fieldName ;

    @Column(name="FIELD_LENGTH", length=100)
    private String     fieldLength ;

    @Column(name="API_URL", length=200)
    private String     apiUrl ;

    @Column(name="DEFAULT_VALUE", length=100)
    private String     defaultValue ;

    @Column(name="VALIDATION_MESSAGE", length=300)
    private String     validationMessage ;

    @Column(name="OPTION_KEYS", length=300)
    private String     optionKeys ;

    @Column(name="OPTION_VALUES", length=300)
    private String     optionValues ;

    @Column(name="PARENT_NAME", length=1000)
    private String     parentName ;

    @Column(name="CHILD_NAME", length=1000)
    private String     childName ;

    @Column(name="REQUEST_KEYS", length=300)
    private String     requestKeys ;

    @Column(name="REQUEST_VALUES", length=300)
    private String     requestValues ;

    @Column(name="REQUEST_TYPE", length=100)
    private String     requestType ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



