/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:53 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "OfsDataDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(OfsDataDetailsId.class)
@Table(name="OFS_DATA_DETAILS")


public class OfsDataDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="QUOTE_NO", nullable=false)
    private BigDecimal quoteNo ;

    @Id
    @Column(name="COVERAGES_ID", nullable=false)
    private BigDecimal coveragesId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Column(name="SCHEME_ID", nullable=false)
    private BigDecimal schemeId ;

    @Id
    @Column(name="LOCATION_ID", nullable=false)
    private BigDecimal locationId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    @Column(name="COVERAGES_SUMINSURED", length=50)
    private String     coveragesSuminsured ;

    @Column(name="PREMIUM_AMOUNT")
    private BigDecimal premiumAmount ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="COVERAGES_Y_N_OPTION", length=1)
    private String     coveragesYNOption ;

    @Column(name="CONTENT_TYPE_ID", nullable=false)
    private BigDecimal contentTypeId ;

    @Column(name="COVERAGES_BASE_RATE")
    private BigDecimal coveragesBaseRate ;

    @Column(name="CALCULATED_SI")
    private BigDecimal calculatedSi ;

    @Column(name="ADJUST_AMOUNT")
    private BigDecimal adjustAmount ;

    @Column(name="REFERRAL_REMARKS", length=4000)
    private String     referralRemarks ;

    @Column(name="COVERAGE_TEXT", length=1000)
    private String     coverageText ;

    @Temporal(TemporalType.DATE)
    @Column(name="COVERAGE_DATE")
    private Date       coverageDate ;

    @Column(name="COVERAGE_CHECK", length=20)
    private String     coverageCheck ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="FIELD_NAME", length=300)
    private String     fieldName ;

    @Column(name="MODULE_ID")
    private BigDecimal moduleId ;

    @Column(name="SCREEN_ID")
    private BigDecimal screenId ;

    @Column(name="SUBSCREEN_ID")
    private BigDecimal subscreenId ;

    @Column(name="FIELDTYPE", length=10)
    private String     fieldtype ;

    @Column(name="COVERAGETYPE", length=1)
    private String     coveragetype ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



