/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-03 ( Date ISO 2022-02-03 - Time 11:31:10 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-03 ( 11:31:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "OfsTransactionDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(OfsTransactionDetailsId.class)
@Table(name="OFS_TRANSACTION_DETAILS")


public class OfsTransactionDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="QUOTE_NO", nullable=false)
    private BigDecimal quoteNo ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Column(name="SCHEME_ID", nullable=false)
    private BigDecimal schemeId ;

    @Id
    @Column(name="COVERAGES_ID", nullable=false)
    private BigDecimal coveragesId ;

    @Id
    @Column(name="COVERAGES_SUB_ID", nullable=false)
    private BigDecimal coveragesSubId ;

    @Id
    @Column(name="MORE_DETAILS_ID", nullable=false)
    private BigDecimal moreDetailsId ;

    @Id
    @Column(name="LOCATION_ID", nullable=false)
    private BigDecimal locationId ;

    @Id
    @Column(name="MODULE_ID", nullable=false)
    private BigDecimal moduleId ;

    @Id
    @Column(name="SCREEN_ID", nullable=false)
    private BigDecimal screenId ;

    @Id
    @Column(name="SUBSCREEN_ID", nullable=false)
    private BigDecimal subscreenId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CONTENT_TYPE_ID", nullable=false)
    private BigDecimal contentTypeId ;

    @Column(name="FIELD_1")
    private String field1 ;

    @Column(name="FIELD_2")
    private String field2 ;

    @Column(name="FIELD_3")
    private String field3 ;

    @Column(name="FIELD_4")
    private String field4 ;

    @Column(name="FIELD_5", length=100)
    private String     field5 ;

    @Column(name="FIELD_6", length=100)
    private String     field6 ;

    @Column(name="FIELD_7", length=100)
    private String     field7 ;

    @Column(name="FIELD_8", length=100)
    private String     field8 ;

    @Column(name="FIELD_9", length=100)
    private String     field9 ;

    @Column(name="FIELD_10", length=100)
    private String     field10 ;

    @Column(name="FIELD_11", length=100)
    private String     field11 ;

    @Column(name="FIELD_12", length=100)
    private String     field12 ;

    @Column(name="FIELD_13")
    private String       field13 ;

    @Column(name="FIELD_14")
    private String       field14 ;

    @Column(name="FIELD_15")
    private String       field15 ;

    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    @Column(name="STATUS", length=1)
    private String     status ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



