/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:54 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "PaymentDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(PaymentDetailId.class)
@Table(name="PAYMENT_DETAIL")


public class PaymentDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="QUOTE_NO", nullable=false)
    private BigDecimal quoteNo ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Column(name="MERCHANT_REFERENCE", nullable=false, length=10)
    private String     merchantReference ;

    //--- ENTITY DATA FIELDS 
    @Column(name="PAYMENT_TYPE", length=100)
    private String     paymentType ;

    @Column(name="PREMIUM")
    private BigDecimal premium ;

    @Column(name="CHEQUE_NO", length=100)
    private String     chequeNo ;

    @Column(name="BANK_NAME", length=100)
    private String     bankName ;

    @Column(name="MICR_CODE", length=100)
    private String     micrCode ;

    @Column(name="CHEQUE_AMOUNT")
    private BigDecimal chequeAmount ;

    @Temporal(TemporalType.DATE)
    @Column(name="CHEQUE_DATE")
    private Date       chequeDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REQUEST_TIME")
    private Date       requestTime ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RESPONSE_TIME")
    private Date       responseTime ;

    @Column(name="RESPONSE_TRAN_NO", length=50)
    private String     responseTranNo ;

    @Column(name="RESPONSE_STATUS", length=50)
    private String     responseStatus ;

    @Column(name="CUSTOMER_EMAIL", length=200)
    private String     customerEmail ;

    @Column(name="CUSTOMER_NAME", length=200)
    private String     customerName ;

    @Column(name="APPLICATION_NO", length=20)
    private String     applicationNo ;

    @Column(name="RESPONSE_MESSAGE", length=200)
    private String     responseMessage ;

    @Column(name="CARD_NUMBER_MASKED", length=200)
    private String     cardNumberMasked ;

    @Column(name="RESPONSE_CODE", length=200)
    private String     responseCode ;

    @Column(name="RES_AUTH_TRANS_REF_NO", length=200)
    private String     resAuthTransRefNo ;

    @Column(name="RES_PAYER_AUTHENTICATION", length=200)
    private String     resPayerAuthentication ;

    @Column(name="RES_REQ_BILL_TO_SURNAME", length=200)
    private String     resReqBillToSurname ;

    @Column(name="RES_REQ_BILL_TO_ADDRESS_CITY", length=200)
    private String     resReqBillToAddressCity ;

    @Column(name="RES_REQ_CARD_EXPIRY_DATE", length=200)
    private String     resReqCardExpiryDate ;

    @Column(name="RES_REQ_POSTAL_CODE", length=200)
    private String     resReqPostalCode ;

    @Column(name="RES_REASON_CODE", length=200)
    private String     resReasonCode ;

    @Column(name="RES_AUTH_AMOUNT", length=200)
    private String     resAuthAmount ;

    @Column(name="RES_AUTH_RESPONSE", length=200)
    private String     resAuthResponse ;

    @Column(name="RES_BILL_TRANS_REF_NO", length=200)
    private String     resBillTransRefNo ;

    @Column(name="RES_REQ_BILL_TO_FORENAME", length=200)
    private String     resReqBillToForename ;

    @Column(name="RES_REQ_PAYMENT_METHOD", length=200)
    private String     resReqPaymentMethod ;

    @Column(name="RES_REQUEST_TOKEN", length=200)
    private String     resRequestToken ;

    @Column(name="RES_AUTH_TIME", length=200)
    private String     resAuthTime ;

    @Column(name="RES_REQ_AMOUNT", length=200)
    private String     resReqAmount ;

    @Column(name="RES_REQ_BILL_TO_EMAIL", length=200)
    private String     resReqBillToEmail ;

    @Column(name="RES_PAYER_AUTH_REASON_CODE", length=200)
    private String     resPayerAuthReasonCode ;

    @Column(name="RES_AUTH_AVS_CODE_RAW", length=200)
    private String     resAuthAvsCodeRaw ;

    @Column(name="RES_TRANSACTION_ID", length=200)
    private String     resTransactionId ;

    @Column(name="RES_REQ_CURRENCY", length=200)
    private String     resReqCurrency ;

    @Column(name="RES_REQ_CARD_TYPE", length=200)
    private String     resReqCardType ;

    @Column(name="RES_PAYER_AUTH_PARES_STATUS", length=200)
    private String     resPayerAuthParesStatus ;

    @Column(name="RES_DECISION", length=200)
    private String     resDecision ;

    @Column(name="RES_PAYER_AUTH_CAVV", length=200)
    private String     resPayerAuthCavv ;

    @Column(name="RES_MESSAGE", length=200)
    private String     resMessage ;

    @Column(name="BRANCH_CODE", length=8)
    private String     branchCode ;

    @Column(name="BILL_TO_FORENAME", length=60)
    private String     billToForename ;

    @Column(name="BILL_TO_SURNAME", length=60)
    private String     billToSurname ;

    @Column(name="BILL_TO_ADDRESS_LINE1", length=60)
    private String     billToAddressLine1 ;

    @Column(name="BILL_TO_ADDRESS_CITY", length=50)
    private String     billToAddressCity ;

    @Column(name="BILL_TO_ADDRESS_COUNTRY", length=2)
    private String     billToAddressCountry ;

    @Column(name="BILL_TO_ADDRESS_POSTAL_CODE", length=10)
    private String     billToAddressPostalCode ;

    @Column(name="BILL_TO_EMAIL", length=255)
    private String     billToEmail ;

    @Column(name="MANUAL_LOGIN_ID", length=50)
    private String     manualLoginId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MANUAL_UPDATE_TIME")
    private Date       manualUpdateTime ;

    @Column(name="MANUAL_STATUS", length=2)
    private String     manualStatus ;

    @Column(name="CURRENCY_TYPE", length=10)
    private String     currencyType ;

    @Column(name="NO_OF_INSTALLMENT")
    private BigDecimal noOfInstallment ;

    @Column(name="INSTALLMENT_AMOUNT")
    private BigDecimal installmentAmount ;

    @Column(name="INSTALLMENT_FREQUENCY", length=20)
    private String     installmentFrequency ;

    @Column(name="INSTALLMENT_START_DATE", length=20)
    private String     installmentStartDate ;

    @Column(name="INSTALLMENT_YN", length=1)
    private String     installmentYn ;

    @Column(name="RES_REQ_TRANSACTION_TYPE", length=100)
    private String     resReqTransactionType ;

    @Column(name="RES_AUTH_CODE", length=100)
    private String     resAuthCode ;

    @Column(name="RES_REQ_RECURRING_FREQUENCY", length=100)
    private String     resReqRecurringFrequency ;

    @Column(name="RES_REQ_NO_OF_INSTALLMENTS", length=100)
    private String     resReqNoOfInstallments ;

    @Column(name="RES_REQ_RECURRING_AMOUNT", length=100)
    private String     resReqRecurringAmount ;

    @Column(name="RES_PAYMENT_TOKEN", length=100)
    private String     resPaymentToken ;

    @Column(name="MOBILE_NO", length=20)
    private String     mobileNo ;

    @Column(name="DEVICE_TYPE", length=20)
    private String     deviceType ;

    @Column(name="INSTALLMENT_NO")
    private BigDecimal installmentNo ;

    @Column(name="INSTALLMENT_REMARKS", length=100)
    private String     installmentRemarks ;

    @Column(name="RISK_ID", length=300)
    private String     riskId ;

    @Column(name="POLICY_NO", length=200)
    private String     policyNo ;

    @Column(name="RENEWAL_YN", length=10)
    private String     renewalYn ;

    @Column(name="REFERENCE_NO", length=2000)
    private String     referenceNo ;

    @Column(name="MTN_MOBILE_NO", length=200)
    private String     mtnMobileNo ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



