/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:55 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "PolicyLocation"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(PolicyLocationId.class)
@Table(name="POLICY_LOCATION")


public class PolicyLocation implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="LOCATION_ID", nullable=false, length=100)
    private String     locationId ;

    @Id
    @Column(name="POLICY_NO", nullable=false, length=100)
    private String     policyNo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="LOCATION_NAME", length=100)
    private String     locationName ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="LOCATION_ADDR", length=100)
    private String     locationAddr ;

    @Column(name="SCHEME_ID")
    private BigDecimal schemeId ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



