/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:55 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "PolicyData"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="POLICY_DATA")


public class PolicyData implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="POLICY_NO", nullable=false)
    private BigDecimal policyNo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="FIRST_NAME", length=100)
    private String     firstName ;

    @Column(name="LAST_NAME", length=100)
    private String     lastName ;

    @Column(name="EMAIL", length=25)
    private String     email ;

    @Column(name="MOBILE_NUMBER", length=100)
    private String     mobileNumber ;

    @Temporal(TemporalType.DATE)
    @Column(name="POLICY_START_DATE")
    private Date       policyStartDate ;

    @Column(name="CUSTOMER_TYPE", length=20)
    private String     customerType ;

    @Column(name="TITLE", length=20)
    private String     title ;

    @Column(name="POLICY_END_DAYS", length=5)
    private String     policyEndDays ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



