/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:56 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "SessionDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(SessionDetailsId.class)
@Table(name="SESSION_DETAILS")


public class SessionDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="LOGIN_ID", nullable=false, length=100)
    private String     loginId ;

    @Id
    @Column(name="TOKEN_ID", nullable=false, length=500)
    private String     tokenId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="BRANCH_CODE", length=50)
    private String     branchCode ;

    @Column(name="BRANCH_NAME", length=50)
    private String     branchName ;

    @Column(name="USERTYPE", length=50)
    private String     usertype ;

    @Column(name="PRODUCT_ID", length=50)
    private String     productId ;

    @Column(name="OPENCOVER_NO", length=100)
    private String     opencoverNo ;

    @Column(name="COUNTRY_ID", length=50)
    private String     countryId ;

    @Column(name="AGENCY_CODE", length=50)
    private String     agencyCode ;

    @Column(name="TEMP_TOKENID", length=500)
    private String     tempTokenid ;

    @Column(name="CURRENCY_NAME", length=30)
    private String     currencyName ;

    @Column(name="MENU_ID", length=150)
    private String     menuId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="REGION_CODE", length=100)
    private String     regionCode ;

    @Column(name="API_LINK", length=2000)
    private String     apiLink ;

    @Column(name="SESSION_ID", length=100)
    private String     sessionId ;

    @Temporal(TemporalType.DATE)
    @Column(name="START_TIME")
    private Date       startTime ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="SYS_IP_ADDRESS", length=20)
    private String     sysIpAddress ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



