/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 19:14:57 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-02-11 ( 19:14:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "SmsConfigMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="SMS_CONFIG_MASTER")


public class SmsConfigMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="INS_ID", nullable=false)
    private BigDecimal insId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SMS_PARTY_URL", length=100)
    private String     smsPartyUrl ;

    @Column(name="SMS_USER_NAME", length=50)
    private String     smsUserName ;

    @Column(name="SMS_USER_PASS", length=50)
    private String     smsUserPass ;

    @Column(name="STATUS", length=5)
    private String     status ;

    @Column(name="SECURE_YN", length=20)
    private String     secureYn ;

    @Column(name="SENDERID", length=20)
    private String     senderid ;

    @Column(name="REMARKS", length=300)
    private String     remarks ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE", nullable=false)
    private Date       effectiveDate ;

    @Column(name="AMENDID", nullable=false)
    private BigDecimal amendid ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRYDATE")
    private Date       entrydate ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



