/*
 * Java domain class for entity "SmsConfigMaster" 
 * Created on 2021-10-13 ( Date ISO 2021-10-13 - Time 12:05:54 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.notification.sms.dto;

import java.io.Serializable;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.maan.common.bean.InsuranceCompanyMaster;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "SmsConfigMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class SmsConfigMasterDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Insid")
    private BigDecimal insId        ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Smspartyurl")
    private String     smsPartyUrl  ;
	@JsonProperty("Smsusername")
    private String     smsUserName  ;
	@JsonProperty("Smsuserpass")
    private String     smsUserPass  ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Secureyn")
    private String     secureYn     ;
	@JsonProperty("Senderid")
    private String     senderid     ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@JsonProperty("Insurancecompanymaster")
    private InsuranceCompanyMasterDto insuranceCompanyMaster ;

      
	  
	  
}
