/*
*  Copyright (c) 2019. All right reserved
* Created on 2021-08-20 ( Date ISO 2021-08-20 - Time 12:06:33 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.common.upload.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.maan.common.bean.ClaimDocumentMaster;
import com.maan.common.upload.request.ClaimDocumentMasterReq;
import com.maan.common.upload.response.ClaimDocumentMasterRes;
import com.maan.common.upload.service.ClaimDocumentMasterService;


/**
* <h2>ClaimDocumentMasterController</h2>
*/
@RestController
@RequestMapping("/api")
public class ClaimDocumentMasterController {

	@Autowired
	private  ClaimDocumentMasterService entityService;

/*
	private static final String ENTITY_TITLE = "ClaimDocumentMaster";


 	public ClaimDocumentMasterController (ClaimDocumentMasterService entityService) {
		this.entityService = entityService;
	}
*/

	@PostMapping(value = "/claimdocumentmaster")
	public ResponseEntity<ClaimDocumentMaster> createClaimDocumentMaster(@RequestBody  ClaimDocumentMaster model) {

   		 ClaimDocumentMaster data = entityService.create(model);
    		if (data != null) {
    			return new ResponseEntity<>(data,HttpStatus.CREATED);
  			  } else {
    			return new ResponseEntity<>(null,HttpStatus.BAD_REQUEST);
   			 }
    }

    @GetMapping(value = "/claimdocumentmaster")
    public ResponseEntity<List<ClaimDocumentMaster>> getAllClaimDocumentMaster() {
        List<ClaimDocumentMaster> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }
    @PostMapping(value = "/claimdoctmaster")
    public ResponseEntity<List<ClaimDocumentMasterRes>> getClaimDocumentMaster(@RequestBody  ClaimDocumentMasterReq req) {
        List<ClaimDocumentMasterRes> lst = entityService.getClaimDocumentMaster(req);

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }
/*
        @GetMapping(value = "/claimdocumentmaster/{id}")
    public ResponseEntity<ClaimDocumentMaster> getOneClaimDocumentMaster(@PathVariable("id") long id) {

            ClaimDocumentMaster e = entityService.getOne(id);
            if (e == null) {
            	return new ResponseEntity<>(null,HttpStatus.NOT_FOUND);
            }
            return new ResponseEntity<>(e, HttpStatus.OK);
    }

*/

}
