/*
*  Copyright (c) 2019. All right reserved
* Created on 2021-07-31 ( Date ISO 2021-07-31 - Time 18:13:33 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.common.master.controller;

import java.util.List;
import com.maan.common.error.Error;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.maan.common.bean.MailMaster;
import com.maan.common.error.CommonValidationException;
import com.maan.common.master.request.MailMasterReq;
import com.maan.common.master.response.MailMasterRes;
import com.maan.common.master.response.sucessRes;
import com.maan.common.master.service.MailMasterService;
import com.maan.common.master.service.PrintReqService;


/**
* <h2>MailMasterController</h2>
*/
@RestController
@RequestMapping("/api")
public class MailMasterController {

	@Autowired
	private  MailMasterService entityService;
	
	@Autowired
	private  PrintReqService dateformat;

	@PostMapping(value = "/getmailmaster")
	public ResponseEntity<List<MailMasterRes>> getmailmaster(@RequestBody  MailMasterReq req) {

		dateformat.reqPrint(req);
		
		List<MailMasterRes> data = entityService.getmailmaster(req);
		if (data != null) {
			return new ResponseEntity<List<MailMasterRes>>(data, HttpStatus.CREATED);
		} else {
			return new ResponseEntity<>(null, HttpStatus.BAD_REQUEST);
		}
	}
	
	@PostMapping(value = "/getmailmasterid")
	public ResponseEntity<MailMasterRes> getmailmasterid(@RequestBody  MailMasterReq req) {

		dateformat.reqPrint(req);
		
		MailMasterRes data = entityService.getmailmasterid(req);
		if (data != null) {
			return new ResponseEntity<MailMasterRes>(data, HttpStatus.CREATED);
		} else {
			return new ResponseEntity<>(null, HttpStatus.BAD_REQUEST);
		}
	}
	
	@PostMapping(value = "/insertmailmaster")
	public ResponseEntity<sucessRes> insertmailmaster(@RequestBody  MailMasterReq req) throws CommonValidationException {

		dateformat.reqPrint(req);
		
	    List<Error> error = entityService.validation(req);
		if (error != null && error.size() > 0)
			throw new CommonValidationException(error, null);
		
		sucessRes data = entityService.insertmailmaster(req);
		if (data != null) {
			return new ResponseEntity<sucessRes>(data, HttpStatus.CREATED);
		} else {
			return new ResponseEntity<>(null, HttpStatus.BAD_REQUEST);
		}
	}

}
