/*
 * Java domain class for entity "BranchMaster" 
 * Created on 2021-07-31 ( Date ISO 2021-07-31 - Time 18:13:32 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2021-07-31 ( 18:13:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;


import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.common.bean.BranchMaster;
import com.maan.common.bean.BranchMasterId;


/**
 * <h2>BranchMasterRepository</h2>
 *
 * createdAt : 2021-07-31 - Time 18:13:32
 * <p>
 * Description: "BranchMaster" Repository
 */
 
 
 
public interface BranchMasterRepository  extends JpaRepository<BranchMaster,BranchMasterId > , JpaSpecificationExecutor<BranchMaster> {


	BranchMaster findByBranchCodeAndInsCompanyId(String branchCode,BigDecimal insCompanyId);

	List<BranchMaster> findByStatusAndRegionCodeAndInsCompanyIdOrderByBranchNameAsc(String status ,String regionCode , BigDecimal insCompanyId);
	List<BranchMaster> OrderByBranchCode();
	
	List<BranchMaster> findByRegionCodeAndInsCompanyIdOrderByBranchNameAsc(String regionCode , BigDecimal insCompanyId);

	List<BranchMaster> findByBranchCode(String string);

	List<BranchMaster> findByBranchCodeAndStatusOrderByAmendIdDesc(String branchCode,
			String string);

	List<BranchMaster> findByBranchCodeAndRegionCodeAndStatus(String branchCode,String regionCode, String string);

	List<BranchMaster> findByRegionCodeAndStatus(String regionCode, String string);

	List<BranchMaster> findByBranchCodeAndStatusOrderByAmendId(String branchCode, String string);
}
