/*
 * Java domain class for entity "BrokerCompanyMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:47 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-13 ( 18:04:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.common.bean.BrokerCompanyMaster;
import com.maan.common.bean.BrokerCompanyMasterId;
/**
 * <h2>BrokerCompanyMasterRepository</h2>
 *
 * createdAt : 2022-01-13 - Time 18:04:47
 * <p>
 * Description: "BrokerCompanyMaster" Repository
 */
 
 
 
public interface BrokerCompanyMasterRepository  extends JpaRepository<BrokerCompanyMaster,BrokerCompanyMasterId > , JpaSpecificationExecutor<BrokerCompanyMaster> {

	List<BrokerCompanyMaster> findByAgencyCode(String agencyCode);
	
	List<BrokerCompanyMaster> findByBranchCodeIn(List<String> branchCode);

	List<BrokerCompanyMaster> findByBranchCode(String branchcode);

	List<BrokerCompanyMaster> findByBranchCodeAndAgencyCodeInOrderByCompanyName(String branchCode,
			List<String> agencycode);

	@Query(value="SELECT CUSTOMER_NUMBER_SEQ.NEXTVAL CUSTOMERID FROM DUAL",nativeQuery=true)
	String getCustomerSeqGenerated();
	
	@Query(value="SELECT BROKER_CODE_SEQ.NEXTVAL BROKERCODE FROM DUAL",nativeQuery=true)
	String getBrokerSeqGenerated();
	@Query(value="SELECT USERCODE_SEQ.NEXTVAL USERCODE FROM DUAL",nativeQuery=true)
	String getUserSeqGenerated();
	
	List<BrokerCompanyMaster> findByRsabrokerCodeAndAgencyCodeAndBranchCode(String brokerCode, String agencyCode,
			String branchCode);

	List<BrokerCompanyMaster> findByRsabrokerCodeAndBranchCode(String brokerCode, String branchCode);

}
