/*
 * Java domain class for entity "BrokerMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:47 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-13 ( 18:04:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.common.bean.BrokerMaster;
/**
 * <h2>BrokerMasterRepository</h2>
 *
 * createdAt : 2022-01-13 - Time 18:04:47
 * <p>
 * Description: "BrokerMaster" Repository
 */
 
 
 
public interface BrokerMasterRepository  extends JpaRepository<BrokerMaster,String > , JpaSpecificationExecutor<BrokerMaster> {

	List<BrokerMaster> findByAgencyCodeAndBranchCode(String agencyCode, String branchCode);

}
