/*
 * Java domain class for entity "CityMaster" 
 * Created on 2022-01-29 ( Date ISO 2022-01-29 - Time 15:25:42 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-29 ( 15:25:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.common.bean.CityMaster;
/**
 * <h2>CityMasterRepository</h2>
 *
 * createdAt : 2022-01-29 - Time 15:25:42
 * <p>
 * Description: "CityMaster" Repository
 */
 
 
 
public interface CityMasterRepository  extends JpaRepository<CityMaster,BigDecimal > , JpaSpecificationExecutor<CityMaster> {

		List<CityMaster> findByCountryIdAndStatus(BigDecimal countryId,String status);
	
}
