/*
 * Java domain class for entity "LoginUserDetails" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-13 ( 18:04:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.google.common.base.Optional;
import com.maan.common.bean.DocumentUploadDetails;
import com.maan.common.bean.DocumentUploadDetailsId;
/**
 * <h2>LoginUserDetailsRepository</h2>
 *
 * createdAt : 2022-01-13 - Time 18:04:48
 * <p>
 * Description: "LoginUserDetails" Repository
 */
 
 
 
public interface DocumentUploadDetailsRepository  extends JpaRepository<DocumentUploadDetails,DocumentUploadDetailsId > , JpaSpecificationExecutor<DocumentUploadDetails> {

	List<DocumentUploadDetails> findByClaimNo(String claimNo);

	List<DocumentUploadDetails> findAllByOrderByDocumentRefDesc();

	Optional<DocumentUploadDetails> findByClaimNoAndDocTypeIdAndDocumentRefAndInsIdAndProductId(String claimnno, String bigDecimal,
			BigDecimal bigDecimal2, BigDecimal bigDecimal3, BigDecimal bigDecimal4);

}
