/*
 * Java domain class for entity "EserviceRequestDetail" 
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 11:40:23 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-02-11 ( 11:40:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.maan.common.bean.EserviceRequestDetail;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.common.bean.EserviceRequestDetailId;
import com.maan.common.bean.OfsData;
/**
 * <h2>EserviceRequestDetailRepository</h2>
 *
 * createdAt : 2022-02-11 - Time 11:40:23
 * <p>
 * Description: "EserviceRequestDetail" Repository
 */
 
 
 
public interface EserviceRequestDetailRepository  extends JpaRepository<EserviceRequestDetail,EserviceRequestDetailId > , JpaSpecificationExecutor<EserviceRequestDetail> {

	Page<EserviceRequestDetail> findByLoginIdAndApplicationIdAndBranchCodeAndProductIdAndStatus(Pageable paging ,String loginId ,String applicationId ,String branchCode , 
			BigDecimal productId , String status   );
	
	Page<EserviceRequestDetail> findByLoginIdAndApplicationIdAndBranchCodeAndProductIdAndStatusAndEntryDateBefore(Pageable paging ,String loginId ,String applicationId ,String branchCode , 
			BigDecimal productId , String status , Date before30   );

	List<EserviceRequestDetail> findByCustomerIdOrderByEntryDateDesc(BigDecimal customerId);
	
	EserviceRequestDetail findByRequestreferencenoAndCustomerIdOrderByEntryDateDesc(String requestreferenceno,BigDecimal customerId);
	
	@Query(value ="SELECT REFERENCE_NO.NEXTVAL FROM dual" , nativeQuery=true)
	String getSeqRefNo();

	Page<EserviceRequestDetail> findByApplicationIdAndBranchCodeAndProductIdAndStatusAndBrokerCode(Pageable paging,
			String applicationid, String branchcode, BigDecimal bigDecimal, String status, String brokerCode);

	Page<EserviceRequestDetail> findByBrokerCodeAndApplicationIdAndBranchCodeAndProductIdAndStatus(Pageable paging,String loginid, String applicationid, String branchcode, BigDecimal bigDecimal, String status);

	Page<EserviceRequestDetail> findByBrokerCodeAndApplicationIdAndBranchCodeAndProductIdAndStatusAndEntryDateBefore(
			Pageable paging, String loginid, String applicationid, String branchcode, BigDecimal bigDecimal,String status, Date before30);
	
	List<EserviceRequestDetail> findByQuoteNoInOrderByEntryDateDesc(List<BigDecimal> quoteNo );
}
