/*
 * Java domain class for entity "HomePositionMaster" 
 * Created on 2022-01-28 ( Date ISO 2022-01-28 - Time 12:57:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-28 ( 12:57:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import com.maan.common.bean.HomePositionMaster;
import com.maan.common.bean.HomePositionMasterId;
/**
 * <h2>HomePositionMasterRepository</h2>
 *
 * createdAt : 2022-01-28 - Time 12:57:40
 * <p>
 * Description: "HomePositionMaster" Repository
 */
 
 
 
public interface HomePositionMasterRepository  extends JpaRepository<HomePositionMaster,HomePositionMasterId > , JpaSpecificationExecutor<HomePositionMaster> {

	 @Query(value = "SELECT (CUSTOMER_ID_SEQ.NEXTVAL) FROM DUAL" , nativeQuery =true)
	 String getSeqCustId();
	 
	HomePositionMaster findByQuoteNo(BigDecimal quoteNo);

	// Non Motor Jpa Quries *******************//
	Page<HomePositionMaster> findByStatusAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndSchemeIdAndCustApproveStatusAndEntryDateAfterAndRemarksOrRemarksNot( Pageable page,String status,
			String loginId,String applicationId , BigDecimal productId, String branchCode,BigDecimal schemeId , String custApproveStatus,  Date before30 ,String data, String remarks);

	Page<HomePositionMaster> findByStatusAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndSchemeIdAndRemarks( Pageable paging, String status, String loginid, 
			String applicationid, BigDecimal productId, String branchcode, BigDecimal schemeId, String remarks);

	Page<HomePositionMaster> findByStatusAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndSchemeIdAndRemarksAndPaymentStatusIsNull( Pageable paging, String status, 
			String loginid, String applicationid, BigDecimal productId, String branchcode, BigDecimal schemeId, String remarks);

	Page<HomePositionMaster> findByStatusAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndSchemeIdAndRemarksAndAdminReferralStatusAndPaymentStatusIsNull( Pageable paging,
			String status, String loginid, String applicationid, BigDecimal productId, String branchcode, BigDecimal schemeId, String remarks, String adminReferalStatus);
	
	Page<HomePositionMaster> findByStatusAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndSchemeIdAndIntegrationErrorIsNull( Pageable paging, String status, String loginid, 
			String applicationid, BigDecimal productId, String branchcode, BigDecimal schemeId);
	
	Page<HomePositionMaster> findByStatusAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndSchemeIdAndPolicyNoIsNotNull( Pageable paging, String status, String loginid, 
			String applicationid, BigDecimal productId, String branchcode, BigDecimal schemeId);
	
	Page<HomePositionMaster> findByLoginIdAndApplicationIdAndProductIdAndBranchCodeAndSchemeIdAndIntegrationStatus( Pageable paging, String loginid, 
			String applicationid, BigDecimal productId, String branchcode, BigDecimal schemeId ,String integStatus);

	List<HomePositionMaster> findByLoginIdAndApplicationIdAndProductIdAndBranchCodeAndSchemeIdAndQuoteNoOrderByQuoteNoDesc(String loginid,
			String applicationid, BigDecimal productId, String branchcode, BigDecimal schemeId ,BigDecimal quoteNo);
	
	List<HomePositionMaster> findByStatusInAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndSchemeIdAndEntryDateBetweenOrderByQuoteNoDesc(List<String> status,
			String loginId,String applicationId , BigDecimal productId, String branchCode,BigDecimal schemeId , Date startDate , Date endDate);

	// Madison Motor Jpa Queries *******************//
	Page<HomePositionMaster> findByStatusAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndCustApproveStatusAndEntryDateAfterAndRemarksOrRemarksNot(Pageable paging, 
			String string, String loginid, String applicationid, BigDecimal bigDecimal, String branchcode, String custAppStatus, Date before30, Object object, String remarksNot);

	Page<HomePositionMaster> findByStatusAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndRemarks(Pageable paging,
			String status, String loginid, String applicationid, BigDecimal bigDecimal, String branchcode, String remarks);

	Page<HomePositionMaster> findByStatusAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndRemarksAndPaymentStatusIsNull(Pageable paging, 
			String status, String loginid, String applicationid, BigDecimal bigDecimal, String branchcode, String remarks);

	Page<HomePositionMaster> findByStatusAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndRemarksAndAdminReferralStatusAndPaymentStatusIsNull(Pageable paging, 
			String status, String loginid, String applicationid, BigDecimal bigDecimal, String branchcode, String remarks, String adminReferalStatus);

	Page<HomePositionMaster> findByStatusAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndIntegrationErrorIsNull( Pageable paging,
			String status, String loginid, String applicationid, BigDecimal bigDecimal, String branchcode);

	Page<HomePositionMaster> findByStatusAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndPolicyNoIsNotNull(Pageable paging, 
			String status, String loginid, String applicationid, BigDecimal bigDecimal,String branchcode);

	Page<HomePositionMaster> findByLoginIdAndApplicationIdAndProductIdAndBranchCodeAndIntegrationStatus(Pageable paging,
			String loginid, String applicationid, BigDecimal bigDecimal, String branchcode, String integStatus);

	List<HomePositionMaster> findByLoginIdAndApplicationIdAndProductIdAndBranchCodeAndQuoteNoOrderByQuoteNoDesc(
			String loginid, String applicationid, BigDecimal bigDecimal, String branchcode, BigDecimal bigDecimal2);

	List<HomePositionMaster> findByLoginIdAndApplicationIdAndProductIdAndBranchCodeAndCustomerIdOrderByEntryDateDesc(
			String loginid, String applicationid, BigDecimal bigDecimal, String branchcode, BigDecimal bigDecimal2);

	List<HomePositionMaster> findByStatusInAndLoginIdAndApplicationIdAndProductIdAndBranchCodeAndEntryDateBetweenOrderByQuoteNoDesc(
			List<String> status, String loginid, String applicationid, BigDecimal bigDecimal, String branchcode,
			Date startDate, Date endDate);

	Page<HomePositionMaster> findByStatusAndBrokerCodeAndApplicationIdAndProductIdAndBranchCodeAndCustApproveStatusAndEntryDateAfterAndRemarksOrRemarksNot(
			Pageable paging, String string, String loginid, String applicationid, BigDecimal bigDecimal, String branchcode, String custAppStatus, Date before30, Object object, String remarksNot);

	Page<HomePositionMaster> findByStatusAndBrokerCodeAndApplicationIdAndProductIdAndBranchCodeAndRemarks(Pageable paging, String status, 
			String loginid, String applicationid, BigDecimal bigDecimal,String branchcode, String remarks);

	Page<HomePositionMaster> findByStatusAndBrokerCodeAndApplicationIdAndProductIdAndBranchCodeAndRemarksAndPaymentStatusIsNull(Pageable paging, String status,
			String loginid, String applicationid, BigDecimal bigDecimal,String branchcode, String remarks);

	Page<HomePositionMaster> findByStatusAndBrokerCodeAndApplicationIdAndProductIdAndBranchCodeAndRemarksAndAdminReferralStatusAndPaymentStatusIsNull(Pageable paging,
			String status, String loginid, String applicationid, BigDecimal bigDecimal,String branchcode, String remarks, String adminReferalStatus);

	Page<HomePositionMaster> findByStatusAndBrokerCodeAndApplicationIdAndProductIdAndBranchCodeAndIntegrationErrorIsNull(
			Pageable paging, String status, String loginid, String applicationid, BigDecimal bigDecimal,String branchcode);

	Page<HomePositionMaster> findByStatusAndBrokerCodeAndApplicationIdAndProductIdAndBranchCodeAndPolicyNoIsNotNull(
			Pageable paging, String status, String loginid, String applicationid, BigDecimal bigDecimal,String branchcode);

	Page<HomePositionMaster> findByBrokerCodeAndApplicationIdAndProductIdAndBranchCodeAndIntegrationStatus(
			Pageable paging, String loginid, String applicationid, BigDecimal bigDecimal, String branchcode,String integStatus);

	List<HomePositionMaster> findByStatusInAndBrokerCodeAndApplicationIdAndProductIdAndBranchCodeAndEntryDateBetweenOrderByQuoteNoDesc(
			List<String> status, String loginid, String applicationid, BigDecimal bigDecimal, String branchcode,
			Date startDate, Date endDate);

	List<HomePositionMaster> findByQuoteNoIn(List<BigDecimal> quoteNos);

	Page<HomePositionMaster> findByStatusInAndLoginIdInAndProductIdAndRemarks(Pageable paging, List<String> status,
			List<String> brokerLoginIds, BigDecimal bigDecimal, String remarks);

	Page<HomePositionMaster> findByStatusInAndLoginIdInAndProductIdAndBranchCodeAndRemarks(Pageable paging,
			List<String> status, List<String> brokerLoginIds, BigDecimal bigDecimal, String branchcode, String remarks);
	
	Page<HomePositionMaster> findByStatusAndLoginIdInAndProductIdAndAdminReferralStatus(Pageable paging, String status,
			List<String> brokerLoginIds, BigDecimal bigDecimal,   String     adminReferralStatus);
	
	Page<HomePositionMaster> findByStatusAndLoginIdInAndProductIdAndBranchCodeAndAdminReferralStatus(Pageable paging,
			String status, List<String> brokerLoginIds, BigDecimal bigDecimal, String branchcode ,String     adminReferralStatus);

	Page<HomePositionMaster> findByStatusAndLoginIdInAndProductIdAndEntryDateGreaterThanEqualAndEntryDateLessThanEqual(
			Pageable paging, String status, List<String> brokerLoginIds, BigDecimal bigDecimal, Date parse,
			Date parse2);


}
