/*
 * Java domain class for entity "InsuranceCompanyMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-13 ( 18:04:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.common.bean.InsuranceCompanyMaster;
/**
 * <h2>InsuranceCompanyMasterRepository</h2>
 *
 * createdAt : 2022-01-13 - Time 18:04:48
 * <p>
 * Description: "InsuranceCompanyMaster" Repository
 */
 
 
 
public interface InsuranceCompanyMasterRepository  extends JpaRepository<InsuranceCompanyMaster,BigDecimal > , JpaSpecificationExecutor<InsuranceCompanyMaster> {

}
