/*
 * Java domain class for entity "MailMaster" 
 * Created on 2021-07-31 ( Date ISO 2021-07-31 - Time 18:13:33 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2021-07-31 ( 18:13:33 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.common.bean.MailMaster;
import com.maan.common.bean.MailMasterId;
/**
 * <h2>MailMasterRepository</h2>
 *
 * createdAt : 2021-07-31 - Time 18:13:33
 * <p>
 * Description: "MailMaster" Repository
 */
 
 
 
public interface MailMasterRepository  extends JpaRepository<MailMaster,MailMasterId > , JpaSpecificationExecutor<MailMaster> {

	List<MailMaster> findByInsCompanyId(BigDecimal insCompanyId);

}
