/*
 * Java domain class for entity "MenuMaster" 
 * Created on 2022-01-29 ( Date ISO 2022-01-29 - Time 15:25:45 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-29 ( 15:25:45 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.common.auth.dto.Menu;
import com.maan.common.bean.MenuMaster;
/**
 * <h2>MenuMasterRepository</h2>
 *
 * createdAt : 2022-01-29 - Time 15:25:45
 * <p>
 * Description: "MenuMaster" Repository
 */
 
 
 
public interface MenuMasterRepository  extends JpaRepository<MenuMaster,BigDecimal > , JpaSpecificationExecutor<MenuMaster> {

	@Query(value="select * from menu_master where usertype like  '%'||?2||'%' and status='Y' and MENU_ID in(?1)", nativeQuery=true)
	List<MenuMaster> findBymenuList(List<String> productId,String usertype);
	
	List<MenuMaster> findByStatusAndBranchCodeAndProductIdAndUsertype(String status,String branchCode,BigDecimal productId,String usertype);

	List<MenuMaster> findByProductIdAndBranchCodeAndMenuIdNotIn(String productId, String branchCode,
			List<BigDecimal> menuId);

}
