/*
 * Java domain class for entity "MFieldMaster" 
 * Created on 2022-01-19 ( Date ISO 2022-01-19 - Time 12:54:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-19 ( 12:54:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.common.bean.MFieldMaster;
/**
 * <h2>MFieldMasterRepository</h2>
 *
 * createdAt : 2022-01-19 - Time 12:54:40
 * <p>
 * Description: "MFieldMaster" Repository
 */
 
 
 
public interface MFieldMasterRepository  extends JpaRepository<MFieldMaster,BigDecimal > , JpaSpecificationExecutor<MFieldMaster> {

	List<MFieldMaster> OrderByMfFieldidAsc();
	
}
