/*
 * Java domain class for entity "MotorQuarterpremDiscounts" 
 * Created on 2022-01-17 ( Date ISO 2022-01-17 - Time 16:33:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-17 ( 16:33:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.common.bean.MotorQuarterpremDiscounts;
import com.maan.common.bean.MotorQuarterpremDiscountsId;
/**
 * <h2>MotorQuarterpremDiscountsRepository</h2>
 *
 * createdAt : 2022-01-17 - Time 16:33:40
 * <p>
 * Description: "MotorQuarterpremDiscounts" Repository
 */
 
 
 
public interface MotorQuarterpremDiscountsRepository  extends JpaRepository<MotorQuarterpremDiscounts,MotorQuarterpremDiscountsId > , JpaSpecificationExecutor<MotorQuarterpremDiscounts> {
 @Query(value="Select Discount_Perc  From Motor_Quarterprem_Discounts where trunc(EFFECTIVE_DATE) < trunc(sysdate) and  case when ?1>399 then 399 else  ?1 end  Between   Startrange And Endrange And Policytype_Id=100 and Product_id=?2", nativeQuery=true)
	BigDecimal getDiscountPremium(long noofdays,String productid);

}
