/*
 * Java domain class for entity "MotorDataDetail" 
 * Created on 2022-01-29 ( Date ISO 2022-01-29 - Time 17:23:19 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-29 ( 17:23:19 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.common.bean.MotorDataDetail;
import com.maan.common.bean.MotorDataDetailId;
/**
 * <h2>MotorDataDetailRepository</h2>
 *
 * createdAt : 2022-01-29 - Time 17:23:19
 * <p>
 * Description: "MotorDataDetail" Repository
 */
 
 
 
public interface MotorDataDetailRepository  extends JpaRepository<MotorDataDetail,MotorDataDetailId > , JpaSpecificationExecutor<MotorDataDetail> {

	List<MotorDataDetail> findByQuoteNo(BigDecimal bigDecimal);
	List<MotorDataDetail> findByCustomerId(BigDecimal bigDecimal);
	MotorDataDetail findByApplicationNoAndVehicleId(BigDecimal bigDecimal, BigDecimal bigDecimal2);
	MotorDataDetail findByApplicationNo(BigDecimal applicationNo);
	@Query(value="SELECT REFERRAL_REMARKS FROM MOTOR_DATA_DETAIL WHERE APPLICATION_NO=?1 AND VEHICLE_ID=?2",nativeQuery=true)
	String getReferralRemarks(BigDecimal bigDecimal, BigDecimal bigDecimal2);
	

}
