/*
 * Java domain class for entity "MsCustomerDetail" 
 * Created on 2022-02-11 ( Date ISO 2022-02-11 - Time 11:40:35 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-02-11 ( 11:40:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;

import com.maan.common.bean.MsCustomerDetail;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
/**
 * <h2>MsCustomerDetailRepository</h2>
 *
 * createdAt : 2022-02-11 - Time 11:40:35
 * <p>
 * Description: "MsCustomerDetail" Repository
 */
 
 
 
public interface MsCustomerDetailRepository  extends JpaRepository<MsCustomerDetail,BigDecimal > , JpaSpecificationExecutor<MsCustomerDetail> {

}
