/*
 * Java domain class for entity "NotifTemplateMaster" 
 * Created on 2022-02-02 ( Date ISO 2022-02-02 - Time 15:32:53 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-02-02 ( 15:32:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.common.bean.NotifTemplateMaster;
import com.maan.common.bean.NotifTemplateMasterId;
/**
 * <h2>NotifTemplateMasterRepository</h2>
 *
 * createdAt : 2022-02-02 - Time 15:32:53
 * <p>
 * Description: "NotifTemplateMaster" Repository
 */
 
 
 
public interface NotifTemplateMasterRepository  extends JpaRepository<NotifTemplateMaster,NotifTemplateMasterId > , JpaSpecificationExecutor<NotifTemplateMaster> {

	NotifTemplateMaster findByInsIdAndStatusAndRemarks(BigDecimal bigDecimal, String string,
			String notificationTemplateId);

	List<NotifTemplateMaster> findBySnoAndStatusAndInsIdAndEffectiveDateBetweenOrderByAmendidDesc(BigDecimal sno,
			String status, BigDecimal insId, Date effectiveDatefrom, Date effectiveDateto);

	List<NotifTemplateMaster> findByInsIdOrderBySnoDesc(BigDecimal insId);

	List<NotifTemplateMaster> findByInsIdOrderByEntryDateDesc(BigDecimal insId);

	List<NotifTemplateMaster> findBySnoAndStatusAndInsIdOrderByEntryDateDesc(BigDecimal sno, String status,
			BigDecimal insId);

}
