/*
 * Java domain class for entity "OfsConfigMaster" 
 * Created on 2022-01-22 ( Date ISO 2022-01-22 - Time 18:25:35 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-22 ( 18:25:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.common.bean.OfsConfigMaster;
import com.maan.common.bean.OfsConfigMasterId;
/**
 * <h2>OfsConfigMasterRepository</h2>
 *
 * createdAt : 2022-01-22 - Time 18:25:35
 * <p>
 * Description: "OfsConfigMaster" Repository
 */
 
 
 
public interface OfsConfigMasterRepository  extends JpaRepository<OfsConfigMaster,OfsConfigMasterId > , JpaSpecificationExecutor<OfsConfigMaster> {

	List<OfsConfigMaster> findByModuleIdAndScreenIdAndSubscreenIdAndCoveragesIdOrderByOfsConfigIdAsc(BigDecimal moduleId ,BigDecimal screenId,BigDecimal subscreenId,BigDecimal coveragesId );

	List<OfsConfigMaster> findByModuleIdAndScreenIdAndSubscreenIdAndCoveragesIdOrderByOfsConfigIdDesc(BigDecimal moduleId ,BigDecimal screenId,BigDecimal subscreenId,BigDecimal coveragesId );

	OfsConfigMaster findByModuleIdAndScreenIdAndSubscreenIdAndCoveragesIdAndCoveragesSubIdAndOfsConfigId(BigDecimal moduleId ,BigDecimal screenId,
			BigDecimal subscreenId,BigDecimal coveragesId  , BigDecimal ofsConfigId ,BigDecimal coveragesSubId);
	
}
