/*
 * Java domain class for entity "OfsTransactionDetails" 
 * Created on 2022-01-22 ( Date ISO 2022-01-22 - Time 18:25:35 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-22 ( 18:25:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.transaction.annotation.Transactional;

import com.maan.common.bean.OfsTransactionDetails;
import com.maan.common.bean.OfsTransactionDetailsId;
/**
 * <h2>OfsTransactionDetailsRepository</h2>
 *
 * createdAt : 2022-01-22 - Time 18:25:35
 * <p>
 * Description: "OfsTransactionDetails" Repository
 */
 
 
 
public interface OfsTransactionDetailsRepository  extends JpaRepository<OfsTransactionDetails,OfsTransactionDetailsId > , JpaSpecificationExecutor<OfsTransactionDetails> {

	@Transactional
	@Modifying
	void save(Map<String, String> data2);

	List<OfsTransactionDetails> findByQuoteNoAndLocationIdAndModuleIdAndScreenIdAndSubscreenIdAndCoveragesIdOrderByMoreDetailsIdDesc(
			BigDecimal quoteNo,BigDecimal locationId ,	BigDecimal moduleId, BigDecimal screenId, BigDecimal subScreenId, BigDecimal coveragesId );

	List<OfsTransactionDetails> findByQuoteNoAndLocationIdAndModuleIdAndScreenIdAndSubscreenIdAndCoveragesIdOrderByMoreDetailsIdAsc(
			BigDecimal quoteNo,BigDecimal locationId ,	BigDecimal moduleId, BigDecimal screenId, BigDecimal subScreenId, BigDecimal coveragesId );
	
	List<OfsTransactionDetails> findByQuoteNoAndLocationIdAndModuleIdAndScreenIdAndSubscreenIdAndCoveragesIdAndMoreDetailsId(
			BigDecimal quoteNo,BigDecimal locationId ,	BigDecimal moduleId, BigDecimal screenId, BigDecimal subScreenId, BigDecimal coveragesId ,
			BigDecimal moreDetailsId);
	
}
