/*
 * Java domain class for entity "PersonalInfo" 
 * Created on 2022-01-28 ( Date ISO 2022-01-28 - Time 12:57:46 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-28 ( 12:57:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.common.bean.PersonalInfo;
/**
 * <h2>PersonalInfoRepository</h2>
 *
 * createdAt : 2022-01-28 - Time 12:57:46
 * <p>
 * Description: "PersonalInfo" Repository
 */
 
 
 
public interface PersonalInfoRepository  extends JpaRepository<PersonalInfo,BigDecimal > , JpaSpecificationExecutor<PersonalInfo> {

	 @Query(value = "SELECT (CUSTOMER_ID_SEQ.NEXTVAL) FROM DUAL" , nativeQuery =true)
	 String getSeqCustId();
	 
	PersonalInfo findByCustomerId(BigDecimal customerId);

	List<PersonalInfo> findByCustomerIdInOrderByEntryDateDesc(List<BigDecimal> customerIds);

	List<PersonalInfo> findByLoginIdInOrderByCustomerIdDesc(List<String> brokerLoginIds);

	PersonalInfo findByAgencyCode(String agencyCode);


	PersonalInfo findByAgencyCodeAndApplicationId(String agencyCode, String applicationId);
	
	List<PersonalInfo> findByAgencyCodeAndApplicationIdIn(String agencyCode,List<String> applicationId);
	
	List<PersonalInfo> findByAgencyCodeAndApplicationIdInOrderByAmendIdDesc(String agencyCode,List<String> applicationId);
	
}