/*
 * Java domain class for entity "PolicytypeMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-13 ( 18:04:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.common.bean.PolicytypeMaster;
import com.maan.common.bean.PolicytypeMasterId;
/**
 * <h2>PolicytypeMasterRepository</h2>
 *
 * createdAt : 2022-01-13 - Time 18:04:49
 * <p>
 * Description: "PolicytypeMaster" Repository
 */
 
 
 
public interface PolicytypeMasterRepository  extends JpaRepository<PolicytypeMaster,PolicytypeMasterId > , JpaSpecificationExecutor<PolicytypeMaster> {

}
