/*
 * Java domain class for entity "ProductMaster" 
 * Created on 2022-01-13 ( Date ISO 2022-01-13 - Time 18:04:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-01-13 ( 18:04:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.common.repository;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.common.bean.ProductMaster;
import com.maan.common.bean.ProductMasterId;
/**
 * <h2>ProductMasterRepository</h2>
 *
 * createdAt : 2022-01-13 - Time 18:04:49
 * <p>
 * Description: "ProductMaster" Repository
 */
 
 
 
public interface ProductMasterRepository  extends JpaRepository<ProductMaster,ProductMasterId > , JpaSpecificationExecutor<ProductMaster> {

	ProductMaster findByProductId(BigDecimal productId);

	List<ProductMaster> findByProductIdNotInAndBranchCodeAndStatusOrderByProductId(List<BigDecimal> productId,
			String branchCode, String string);

	List<ProductMaster> findByBranchCodeAndStatusOrderByProductId(String belongingBranch, String string);

	List<ProductMaster> findByProductIdAndBranchCodeAndStatusOrderByProductId(BigDecimal productId,
			String branchCode, String string);

	List<ProductMaster> findByStatusAndBranchCode(String belongingBranch, String string);

	List<ProductMaster> findByStatusAndProductIdNotInAndBranchCode(String string, List<BigDecimal> product,
			String belongingBranch);
	
	ProductMaster findByProductIdAndStatus(BigDecimal productId,String status);

	List<ProductMaster> findByStatusAndProductIdNotIn(String string, List<String> product);
}
