/*
 * Java domain class for entity "MailMaster" 
 * Created on 2021-10-12 ( Date ISO 2021-10-12 - Time 12:43:33 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.common.notification.mail.dto;

import java.io.Serializable;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "MailMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class MailMaster implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Applicationid")
    private String     applicationId ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Mailcc")
    private String     mailCc       ;
	@JsonProperty("Smtphost")
    private String     smtpHost     ;
	@JsonProperty("Smtpuser")
    private String     smtpUser     ;
	@JsonProperty("Smtppwd")
    private String     smtpPwd      ;
	@JsonProperty("Expdate")
    private String     expDate      ;
	@JsonProperty("Exptime")
    private String     expTime      ;
	@JsonProperty("Pwdcnt")
    private BigDecimal pwdCnt       ;
	@JsonProperty("Pwdlen")
    private String pwdLen       ;
	@JsonProperty("Homeapplicationid")
    private String     homeApplicationId ;
	@JsonProperty("Address")
    private String     address      ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Remarks")
    private String     remarks      ;
	@JsonProperty("Companyname")
    private String     companyName  ;
	@JsonProperty("Toaddress")
    private String     toAddress    ;
	@JsonProperty("Authorizyn")
    private String     authorizYn   ;
	@JsonProperty("Smtpport")
    private BigDecimal smtpPort     ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
