/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2021-08-03 ( String ISO 2021-08-03 - Time 18:07:25 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2021-08-03 ( 18:07:25 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.common.master.response;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class sucessRes  {
	
	@JsonProperty("Response")
	private String response;
}
